
/*
* HistoryConfigurationDialog.java
*
* Created on July 27, 2006, 3:39 PM
 */
package tr.com.srdc.icardea.careplanengine.agents.gui.util;

//~--- JDK imports ------------------------------------------------------------

import java.awt.*;

import javax.swing.*;

/**
 *
 * @author  mehmet
 */
public class StatusDialog extends javax.swing.JDialog {
    private static boolean isCancelled;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel  statusLabel;

    // End of variables declaration//GEN-END:variables

    private Thread              threadToBeWaited;

    /** Creates new form HistoryConfigurationDialog */
    private StatusDialog(JFrame parent, Thread thread, String message) {
        super(parent, true);
        this.threadToBeWaited = thread;
        initComponents();
        statusLabel.setFont(new Font("Times New Roman", Font.PLAIN, 14));
        setTitle("Waiting for unfinished work in background...");
        setDisplayText(message);
        setLocationRelativeTo(parent);
        isCancelled = false;
        new Thread() {
            public void run() {
                while (threadToBeWaited.isAlive()) {
                    try {
                        sleep(500);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }

                StatusDialog.this.dispose();
            }
        }.start();
        setVisible(true);
    }

    public void setDisplayText(String displayText) {
        statusLabel.setText(displayText);
        pack();
    }

    public static boolean showStatusDialog(JFrame parent, Thread thread, String message) {
        new StatusDialog(parent, thread, message);

        return isCancelled;
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        statusLabel  = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Configure History");
        statusLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        statusLabel.setText("Status Here");
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());

        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                        layout.createSequentialGroup().add(
                            statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE).add(
                            18, 18, 18)).add(
                                org.jdesktop.layout.GroupLayout.TRAILING,
                                layout.createSequentialGroup().add(
                                    cancelButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103,
                                    org.jdesktop.layout.GroupLayout.PREFERRED_SIZE).addContainerGap()))));
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING).add(
                layout.createSequentialGroup().addContainerGap().add(
                    statusLabel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE).addPreferredGap(
                    org.jdesktop.layout.LayoutStyle.RELATED).add(cancelButton).addContainerGap()));
        pack();
    }    // </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {    // GEN-FIRST:event_cancelButtonActionPerformed
        isCancelled = true;
        this.dispose();
    }    // GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

//              new HistoryConfigurationDialog(this).setVisible(true);
            }
        });
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
