package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Alarm_Entity
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Alarm_Entity extends Medical_Knowledge_Layer {

    // Property http://www.owl-ontologies.com/unnamed.owl#agent_id
    String getAgent_id();

    RDFProperty getAgent_idProperty();

    boolean hasAgent_id();

    void setAgent_id(String newAgent_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#alarm_message
    String getAlarm_message();

    RDFProperty getAlarm_messageProperty();

    boolean hasAlarm_message();

    void setAlarm_message(String newAlarm_message);

    // Property http://www.owl-ontologies.com/unnamed.owl#alarm_threshold
    String getAlarm_threshold();

    RDFProperty getAlarm_thresholdProperty();

    boolean hasAlarm_threshold();

    void setAlarm_threshold(String newAlarm_threshold);

    // Property http://www.owl-ontologies.com/unnamed.owl#patient_id
    String getPatient_id();

    RDFProperty getPatient_idProperty();

    boolean hasPatient_id();

    void setPatient_id(String newPatient_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#roles
    Collection getRoles();

    RDFProperty getRolesProperty();

    boolean hasRoles();

    Iterator listRoles();

    void addRoles(String newRoles);

    void removeRoles(String oldRoles);

    void setRoles(Collection newRoles);
}


//~ Formatted by Jindent --- http://www.jindent.com
