package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Atomic_Frequency
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Atomic_Frequency extends GLIF_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#frequency
    Frequency_Expression getFrequency();

    RDFProperty getFrequencyProperty();

    boolean hasFrequency();

    void setFrequency(Frequency_Expression newFrequency);

    // Property http://www.owl-ontologies.com/unnamed.owl#until
    Criterion getUntil();

    RDFProperty getUntilProperty();

    boolean hasUntil();

    void setUntil(Criterion newUntil);
}


//~ Formatted by Jindent --- http://www.jindent.com
