package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#AttributeDescription
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface AttributeDescription extends Core_GLIF_Class {

    // Property http://www.owl-ontologies.com/unnamed.owl#cardinality
    String getCardinality();

    RDFProperty getCardinalityProperty();

    boolean hasCardinality();

    void setCardinality(String newCardinality);

    // Property http://www.owl-ontologies.com/unnamed.owl#domain
    Collection getDomain();

    RDFProperty getDomainProperty();

    boolean hasDomain();

    Iterator listDomain();

    void addDomain(Concept newDomain);

    void removeDomain(Concept oldDomain);

    void setDomain(Collection newDomain);

    // Property http://www.owl-ontologies.com/unnamed.owl#name2
    String getName2();

    RDFProperty getName2Property();

    boolean hasName2();

    void setName2(String newName2);
}


//~ Formatted by Jindent --- http://www.jindent.com
