package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Branch_Step
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Branch_Step extends Guideline_Step {

    // Property http://www.owl-ontologies.com/unnamed.owl#branches
    Collection getBranches();

    RDFProperty getBranchesProperty();

    boolean hasBranches();

    Iterator listBranches();

    void addBranches(Guideline_Step newBranches);

    void removeBranches(Guideline_Step oldBranches);

    void setBranches(Collection newBranches);

    // Property http://www.owl-ontologies.com/unnamed.owl#order_constraint
    String getOrder_constraint();

    RDFProperty getOrder_constraintProperty();

    boolean hasOrder_constraint();

    void setOrder_constraint(String newOrder_constraint);
}


//~ Formatted by Jindent --- http://www.jindent.com
