package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#DataModelAttribute
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface DataModelAttribute extends AttributeDescription {

    // Property http://www.owl-ontologies.com/unnamed.owl#data_model_class_id
    String getData_model_class_id();

    RDFProperty getData_model_class_idProperty();

    boolean hasData_model_class_id();

    void setData_model_class_id(String newData_model_class_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_model_source_id
    String getData_model_source_id();

    RDFProperty getData_model_source_idProperty();

    boolean hasData_model_source_id();

    void setData_model_source_id(String newData_model_source_id);
}


//~ Formatted by Jindent --- http://www.jindent.com
