package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Data_Item_Relationship
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface Data_Item_Relationship extends Core_GLIF_Class {

    // Property http://www.owl-ontologies.com/unnamed.owl#certainty
    int getCertainty();

    RDFProperty getCertaintyProperty();

    boolean hasCertainty();

    void setCertainty(int newCertainty);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_item_from
    Data_Item getData_item_from();

    RDFProperty getData_item_fromProperty();

    boolean hasData_item_from();

    void setData_item_from(Data_Item newData_item_from);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_item_to
    Data_Item getData_item_to();

    RDFProperty getData_item_toProperty();

    boolean hasData_item_to();

    void setData_item_to(Data_Item newData_item_to);

    // Property http://www.owl-ontologies.com/unnamed.owl#directionality
    String getDirectionality();

    RDFProperty getDirectionalityProperty();

    boolean hasDirectionality();

    void setDirectionality(String newDirectionality);

    // Property http://www.owl-ontologies.com/unnamed.owl#name2
    String getName2();

    RDFProperty getName2Property();

    boolean hasName2();

    void setName2(String newName2);

    // Property http://www.owl-ontologies.com/unnamed.owl#relationship_code
    String getRelationship_code();

    RDFProperty getRelationship_codeProperty();

    boolean hasRelationship_code();

    void setRelationship_code(String newRelationship_code);

    // Property http://www.owl-ontologies.com/unnamed.owl#relationship_id
    String getRelationship_id();

    RDFProperty getRelationship_idProperty();

    boolean hasRelationship_id();

    void setRelationship_id(String newRelationship_id);
}


//~ Formatted by Jindent --- http://www.jindent.com
