package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Data_Model_Instance
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Data_Model_Instance extends Data_Item_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#concept
    Concept getConcept();

    RDFProperty getConceptProperty();

    boolean hasConcept();

    void setConcept(Concept newConcept);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_model_class_id
    String getData_model_class_id();

    RDFProperty getData_model_class_idProperty();

    boolean hasData_model_class_id();

    void setData_model_class_id(String newData_model_class_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_model_source_id
    String getData_model_source_id();

    RDFProperty getData_model_source_idProperty();

    boolean hasData_model_source_id();

    void setData_model_source_id(String newData_model_source_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#instance_name
    String getInstance_name();

    RDFProperty getInstance_nameProperty();

    boolean hasInstance_name();

    void setInstance_name(String newInstance_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#values
    Collection getValues();

    RDFProperty getValuesProperty();

    boolean hasValues();

    Iterator listValues();

    void addValues(Instance_Value newValues);

    void removeValues(Instance_Value oldValues);

    void setValues(Collection newValues);
}


//~ Formatted by Jindent --- http://www.jindent.com
