package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#EHR_Entity
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface EHR_Entity extends Data_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#agent_id
    String getAgent_id();

    RDFProperty getAgent_idProperty();

    boolean hasAgent_id();

    void setAgent_id(String newAgent_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#object_ids
    Collection getObject_ids();

    RDFProperty getObject_idsProperty();

    boolean hasObject_ids();

    Iterator listObject_ids();

    void addObject_ids(String newObject_ids);

    void removeObject_ids(String oldObject_ids);

    void setObject_ids(Collection newObject_ids);

    // Property http://www.owl-ontologies.com/unnamed.owl#type
    String getType();

    RDFProperty getTypeProperty();

    boolean hasType();

    void setType(String newType);
}


//~ Formatted by Jindent --- http://www.jindent.com
