package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Generate_Event_Action
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface Generate_Event_Action extends Programming_Oriented_Action_Specification {

    // Property http://www.owl-ontologies.com/unnamed.owl#event
    Event getEvent();

    RDFProperty getEventProperty();

    boolean hasEvent();

    void setEvent(Event newEvent);
}


//~ Formatted by Jindent --- http://www.jindent.com
