package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Get_Conditional_Data_Macro
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Get_Conditional_Data_Macro extends Macro {

    // Property http://www.owl-ontologies.com/unnamed.owl#condition
    Criterion getCondition();

    RDFProperty getConditionProperty();

    boolean hasCondition();

    void setCondition(Criterion newCondition);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_to_get
    Get_Data_Action getData_to_get();

    RDFProperty getData_to_getProperty();

    boolean hasData_to_get();

    void setData_to_get(Get_Data_Action newData_to_get);
}


//~ Formatted by Jindent --- http://www.jindent.com
