package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Guideline_Expression
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Guideline_Expression extends Expression, Guideline_Model_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#Get_Data_Items
    Collection getGet_Data_Items();

    RDFProperty getGet_Data_ItemsProperty();

    boolean hasGet_Data_Items();

    Iterator listGet_Data_Items();

    void addGet_Data_Items(Get_Data_Action newGet_Data_Items);

    void removeGet_Data_Items(Get_Data_Action oldGet_Data_Items);

    void setGet_Data_Items(Collection newGet_Data_Items);

    // Property http://www.owl-ontologies.com/unnamed.owl#Get_Knowledge_Items
    Collection getGet_Knowledge_Items();

    RDFProperty getGet_Knowledge_ItemsProperty();

    boolean hasGet_Knowledge_Items();

    Iterator listGet_Knowledge_Items();

    void addGet_Knowledge_Items(Get_Knowledge_Action newGet_Knowledge_Items);

    void removeGet_Knowledge_Items(Get_Knowledge_Action oldGet_Knowledge_Items);

    void setGet_Knowledge_Items(Collection newGet_Knowledge_Items);

    // Property http://www.owl-ontologies.com/unnamed.owl#didactics
    Collection getDidactics();

    RDFProperty getDidacticsProperty();

    boolean hasDidactics();

    Iterator listDidactics();

    void addDidactics(Supplemental_Material_List newDidactics);

    void removeDidactics(Supplemental_Material_List oldDidactics);

    void setDidactics(Collection newDidactics);

    // Property http://www.owl-ontologies.com/unnamed.owl#let_expressions
    Collection getLet_expressions();

    RDFProperty getLet_expressionsProperty();

    boolean hasLet_expressions();

    Iterator listLet_expressions();

    void addLet_expressions(Let_Expression newLet_expressions);

    void removeLet_expressions(Let_Expression oldLet_expressions);

    void setLet_expressions(Collection newLet_expressions);
}


//~ Formatted by Jindent --- http://www.jindent.com
