package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Index
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface Index extends Observation_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#index
    float getIndex();

    RDFProperty getIndexProperty();

    boolean hasIndex();

    void setIndex(float newIndex);

    // Property http://www.owl-ontologies.com/unnamed.owl#precision
    int getPrecision();

    RDFProperty getPrecisionProperty();

    boolean hasPrecision();

    void setPrecision(int newPrecision);
}


//~ Formatted by Jindent --- http://www.jindent.com
