package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#List_Value
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface List_Value extends Primitive_Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#list_value
    Collection getList_value();

    RDFProperty getList_valueProperty();

    boolean hasList_value();

    Iterator listList_value();

    void addList_value(Basic_Data_Type newList_value);

    void removeList_value(Basic_Data_Type oldList_value);

    void setList_value(Collection newList_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
