package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Macro_Action
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface Macro_Action extends Action_Specification {

    // Property http://www.owl-ontologies.com/unnamed.owl#macro
    Macro getMacro();

    RDFProperty getMacroProperty();

    boolean hasMacro();

    void setMacro(Macro newMacro);
}


//~ Formatted by Jindent --- http://www.jindent.com
