package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Macro_Schema
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface Macro_Schema extends Guideline_Model_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#GLIF_pattern
    Object getGLIF_pattern();

    RDFProperty getGLIF_patternProperty();

    boolean hasGLIF_pattern();

    void setGLIF_pattern(Object newGLIF_pattern);

    // Property http://www.owl-ontologies.com/unnamed.owl#macro_class_name
    String getMacro_class_name();

    RDFProperty getMacro_class_nameProperty();

    boolean hasMacro_class_name();

    void setMacro_class_name(String newMacro_class_name);
}


//~ Formatted by Jindent --- http://www.jindent.com
