package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Macro_Action_Step
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Macro_Action_Step extends Action_Step {}


//~ Formatted by Jindent --- http://www.jindent.com
