package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Medication
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Medication extends Patient_Data {

    // Property http://www.owl-ontologies.com/unnamed.owl#check_dose_quantity
    Physical_Quantity getCheck_dose_quantity();

    RDFProperty getCheck_dose_quantityProperty();

    boolean hasCheck_dose_quantity();

    void setCheck_dose_quantity(Physical_Quantity newCheck_dose_quantity);

    // Property http://www.owl-ontologies.com/unnamed.owl#dosage_quantity
    Physical_Quantity getDosage_quantity();

    RDFProperty getDosage_quantityProperty();

    boolean hasDosage_quantity();

    void setDosage_quantity(Physical_Quantity newDosage_quantity);

    // Property http://www.owl-ontologies.com/unnamed.owl#doseform_cd
    String getDoseform_cd();

    RDFProperty getDoseform_cdProperty();

    boolean hasDoseform_cd();

    void setDoseform_cd(String newDoseform_cd);

    // Property http://www.owl-ontologies.com/unnamed.owl#rate_quantity
    Physical_Quantity getRate_quantity();

    RDFProperty getRate_quantityProperty();

    boolean hasRate_quantity();

    void setRate_quantity(Physical_Quantity newRate_quantity);

    // Property http://www.owl-ontologies.com/unnamed.owl#route_cd
    String getRoute_cd();

    RDFProperty getRoute_cdProperty();

    boolean hasRoute_cd();

    void setRoute_cd(String newRoute_cd);

    // Property http://www.owl-ontologies.com/unnamed.owl#strength_quantity
    Physical_Quantity getStrength_quantity();

    RDFProperty getStrength_quantityProperty();

    boolean hasStrength_quantity();

    void setStrength_quantity(Physical_Quantity newStrength_quantity);
}


//~ Formatted by Jindent --- http://www.jindent.com
