package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Medically_Oriented_Action_Specification
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface Medically_Oriented_Action_Specification extends Action_Specification {

    // Property http://www.owl-ontologies.com/unnamed.owl#medical_task
    Medical_Action_Entity getMedical_task();

    RDFProperty getMedical_taskProperty();

    boolean hasMedical_task();

    void setMedical_task(Medical_Action_Entity newMedical_task);
}


//~ Formatted by Jindent --- http://www.jindent.com
