package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#ObjectLocation
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface ObjectLocation extends Diagram_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#location
    Collection getLocation();

    RDFProperty getLocationProperty();

    boolean hasLocation();

    Iterator listLocation();

    void addLocation(Rectangle newLocation);

    void removeLocation(Rectangle oldLocation);

    void setLocation(Collection newLocation);

    // Property http://www.owl-ontologies.com/unnamed.owl#object
    Collection getObject();

    RDFProperty getObjectProperty();

    boolean hasObject();

    Iterator listObject();

    void addObject(Object newObject);

    void removeObject(Object oldObject);

    void setObject(Collection newObject);
}


//~ Formatted by Jindent --- http://www.jindent.com
