package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Observation_Value
 *
 * @version generated on Thu Jun 08 17:29:55 EEST 2006
 */
public interface Observation_Value extends RIM_Entity {}


//~ Formatted by Jindent --- http://www.jindent.com
