package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#ParameterValue
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface ParameterValue extends Parameter {

    // Property http://www.owl-ontologies.com/unnamed.owl#parameter_value
    Data_Value getParameter_value();

    RDFProperty getParameter_valueProperty();

    boolean hasParameter_value();

    void setParameter_value(Data_Value newParameter_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
