package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Patient_State_Step
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Patient_State_Step extends Guideline_Step {

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    String getDisplay_name();

    RDFProperty getDisplay_nameProperty();

    boolean hasDisplay_name();

    void setDisplay_name(String newDisplay_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#new_encounter
    boolean getNew_encounter();

    RDFProperty getNew_encounterProperty();

    boolean hasNew_encounter();

    void setNew_encounter(boolean newNew_encounter);

    // Property http://www.owl-ontologies.com/unnamed.owl#next_step
    Guideline_Step getNext_step();

    RDFProperty getNext_stepProperty();

    boolean hasNext_step();

    void setNext_step(Guideline_Step newNext_step);

    // Property http://www.owl-ontologies.com/unnamed.owl#patient_state_description
    Criterion getPatient_state_description();

    RDFProperty getPatient_state_descriptionProperty();

    boolean hasPatient_state_description();

    void setPatient_state_description(Criterion newPatient_state_description);
}


//~ Formatted by Jindent --- http://www.jindent.com
