package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Physical_Quantity
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Physical_Quantity extends Observation_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    String getDisplay_name();

    RDFProperty getDisplay_nameProperty();

    boolean hasDisplay_name();

    void setDisplay_name(String newDisplay_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#pq_value
    float getPq_value();

    RDFProperty getPq_valueProperty();

    boolean hasPq_value();

    void setPq_value(float newPq_value);

    // Property http://www.owl-ontologies.com/unnamed.owl#precision
    int getPrecision();

    RDFProperty getPrecisionProperty();

    boolean hasPrecision();

    void setPrecision(int newPrecision);

    // Property http://www.owl-ontologies.com/unnamed.owl#unit
    String getUnit();

    RDFProperty getUnitProperty();

    boolean hasUnit();

    void setUnit(String newUnit);
}


//~ Formatted by Jindent --- http://www.jindent.com
