package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Range
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Range extends Observation_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    String getDisplay_name();

    RDFProperty getDisplay_nameProperty();

    boolean hasDisplay_name();

    void setDisplay_name(String newDisplay_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#lower_bound
    Physical_Quantity getLower_bound();

    RDFProperty getLower_boundProperty();

    boolean hasLower_bound();

    void setLower_bound(Physical_Quantity newLower_bound);

    // Property http://www.owl-ontologies.com/unnamed.owl#upper_bound
    Physical_Quantity getUpper_bound();

    RDFProperty getUpper_boundProperty();

    boolean hasUpper_bound();

    void setUpper_bound(Physical_Quantity newUpper_bound);
}


//~ Formatted by Jindent --- http://www.jindent.com
