package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Set_Value
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public interface Set_Value extends Primitive_Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#set_value
    Collection getSet_value();

    RDFProperty getSet_valueProperty();

    boolean hasSet_value();

    Iterator listSet_value();

    void addSet_value(Basic_Data_Type newSet_value);

    void removeSet_value(Basic_Data_Type oldSet_value);

    void setSet_value(Collection newSet_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
