package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Synchronization_Step
 *
 * @version generated on Thu Jun 08 17:30:03 EEST 2006
 */
public interface Synchronization_Step extends Guideline_Step {

    // Property http://www.owl-ontologies.com/unnamed.owl#continuation
    Logical_Expression_Of_Guideline_Step getContinuation();

    RDFProperty getContinuationProperty();

    boolean hasContinuation();

    void setContinuation(Logical_Expression_Of_Guideline_Step newContinuation);

    // Property http://www.owl-ontologies.com/unnamed.owl#next_step
    Guideline_Step getNext_step();

    RDFProperty getNext_stepProperty();

    boolean hasNext_step();

    void setNext_step(Guideline_Step newNext_step);
}


//~ Formatted by Jindent --- http://www.jindent.com
