package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Time_Stamp_Value
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Time_Stamp_Value extends Primitive_Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#time_stamp
    String getTime_stamp();

    RDFProperty getTime_stampProperty();

    boolean hasTime_stamp();

    void setTime_stamp(String newTime_stamp);
}


//~ Formatted by Jindent --- http://www.jindent.com
