package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Times_Expression
 *
 * @version generated on Thu Jun 08 17:29:55 EEST 2006
 */
public interface Times_Expression extends Frequency_Expression {

    // Property http://www.owl-ontologies.com/unnamed.owl#per
    Duration getPer();

    RDFProperty getPerProperty();

    boolean hasPer();

    void setPer(Duration newPer);

    // Property http://www.owl-ontologies.com/unnamed.owl#repeat_times
    int getRepeat_times();

    RDFProperty getRepeat_timesProperty();

    boolean hasRepeat_times();

    void setRepeat_times(int newRepeat_times);
}


//~ Formatted by Jindent --- http://www.jindent.com
