package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#View_Specification
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface View_Specification extends Guideline_Model_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#filter_expression
    String getFilter_expression();

    RDFProperty getFilter_expressionProperty();

    boolean hasFilter_expression();

    void setFilter_expression(String newFilter_expression);
}


//~ Formatted by Jindent --- http://www.jindent.com
