package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Procedure
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public class DefaultProcedure extends DefaultPatient_Data implements Procedure {
    public DefaultProcedure() {}

    public DefaultProcedure(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#entry_site_cd
    public Concept getEntry_site_cd() {
        return (Concept) getPropertyValueAs(getEntry_site_cdProperty(), Concept.class);
    }

    public RDFProperty getEntry_site_cdProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#entry_site_cd";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEntry_site_cd() {
        return getPropertyValueCount(getEntry_site_cdProperty()) > 0;
    }

    public void setEntry_site_cd(Concept newEntry_site_cd) {
        setPropertyValue(getEntry_site_cdProperty(), newEntry_site_cd);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
