package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Time_Interval
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public class DefaultTime_Interval extends DefaultGlobal_Concepts implements Time_Interval {
    public DefaultTime_Interval() {}

    public DefaultTime_Interval(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    public String getDisplay_name() {
        return (String) getPropertyValue(getDisplay_nameProperty());
    }

    public RDFProperty getDisplay_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#display_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDisplay_name() {
        return getPropertyValueCount(getDisplay_nameProperty()) > 0;
    }

    public void setDisplay_name(String newDisplay_name) {
        setPropertyValue(getDisplay_nameProperty(), newDisplay_name);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#max_time_stamp
    public Time_Literal getMax_time_stamp() {
        return (Time_Literal) getPropertyValueAs(getMax_time_stampProperty(), Time_Literal.class);
    }

    public RDFProperty getMax_time_stampProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#max_time_stamp";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMax_time_stamp() {
        return getPropertyValueCount(getMax_time_stampProperty()) > 0;
    }

    public void setMax_time_stamp(Time_Literal newMax_time_stamp) {
        setPropertyValue(getMax_time_stampProperty(), newMax_time_stamp);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#min_time_stamp
    public Time_Literal getMin_time_stamp() {
        return (Time_Literal) getPropertyValueAs(getMin_time_stampProperty(), Time_Literal.class);
    }

    public RDFProperty getMin_time_stampProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#min_time_stamp";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMin_time_stamp() {
        return getPropertyValueCount(getMin_time_stampProperty()) > 0;
    }

    public void setMin_time_stamp(Time_Literal newMin_time_stamp) {
        setPropertyValue(getMin_time_stampProperty(), newMin_time_stamp);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
