package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#List_Value
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public class DefaultList_Value extends DefaultPrimitive_Data_Value implements List_Value {
    public DefaultList_Value() {}

    public DefaultList_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#list_value
    public Collection getList_value() {
        return getPropertyValuesAs(getList_valueProperty(), Basic_Data_Type.class);
    }

    public RDFProperty getList_valueProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#list_value";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasList_value() {
        return getPropertyValueCount(getList_valueProperty()) > 0;
    }

    public Iterator listList_value() {
        return listPropertyValuesAs(getList_valueProperty(), Basic_Data_Type.class);
    }

    public void addList_value(Basic_Data_Type newList_value) {
        addPropertyValue(getList_valueProperty(), newList_value);
    }

    public void removeList_value(Basic_Data_Type oldList_value) {
        removePropertyValue(getList_valueProperty(), oldList_value);
    }

    public void setList_value(Collection newList_value) {
        setPropertyValues(getList_valueProperty(), newList_value);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
