package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Duration_Interval
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public class DefaultDuration_Interval extends DefaultGlobal_Concepts implements Duration_Interval {
    public DefaultDuration_Interval() {}

    public DefaultDuration_Interval(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    public String getDisplay_name() {
        return (String) getPropertyValue(getDisplay_nameProperty());
    }

    public RDFProperty getDisplay_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#display_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDisplay_name() {
        return getPropertyValueCount(getDisplay_nameProperty()) > 0;
    }

    public void setDisplay_name(String newDisplay_name) {
        setPropertyValue(getDisplay_nameProperty(), newDisplay_name);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#max_duration
    public Duration getMax_duration() {
        return (Duration) getPropertyValueAs(getMax_durationProperty(), Duration.class);
    }

    public RDFProperty getMax_durationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#max_duration";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMax_duration() {
        return getPropertyValueCount(getMax_durationProperty()) > 0;
    }

    public void setMax_duration(Duration newMax_duration) {
        setPropertyValue(getMax_durationProperty(), newMax_duration);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#min_duration
    public Duration getMin_duration() {
        return (Duration) getPropertyValueAs(getMin_durationProperty(), Duration.class);
    }

    public RDFProperty getMin_durationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#min_duration";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMin_duration() {
        return getPropertyValueCount(getMin_durationProperty()) > 0;
    }

    public void setMin_duration(Duration newMin_duration) {
        setPropertyValue(getMin_durationProperty(), newMin_duration);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
