package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#BasicAttribute
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public class DefaultBasicAttribute extends DefaultAttributeDescription implements BasicAttribute {
    public DefaultBasicAttribute() {}

    public DefaultBasicAttribute(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#data_type
    public String getData_type() {
        return (String) getPropertyValue(getData_typeProperty());
    }

    public RDFProperty getData_typeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#data_type";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasData_type() {
        return getPropertyValueCount(getData_typeProperty()) > 0;
    }

    public void setData_type(String newData_type) {
        setPropertyValue(getData_typeProperty(), newData_type);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
