package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Instance_Value
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public class DefaultInstance_Value extends DefaultUser_Defined_Data_Model_Class implements Instance_Value {
    public DefaultInstance_Value() {}

    public DefaultInstance_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#parameter_name
    public String getParameter_name() {
        return (String) getPropertyValue(getParameter_nameProperty());
    }

    public RDFProperty getParameter_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#parameter_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasParameter_name() {
        return getPropertyValueCount(getParameter_nameProperty()) > 0;
    }

    public void setParameter_name(String newParameter_name) {
        setPropertyValue(getParameter_nameProperty(), newParameter_name);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
