package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Conditional_Data_List_Macro
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public class DefaultConditional_Data_List_Macro extends DefaultMacro implements Conditional_Data_List_Macro {
    public DefaultConditional_Data_List_Macro() {}

    public DefaultConditional_Data_List_Macro(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#demographics
    public Collection getDemographics() {
        return getPropertyValuesAs(getDemographicsProperty(), Get_Conditional_Data_Macro.class);
    }

    public RDFProperty getDemographicsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#demographics";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDemographics() {
        return getPropertyValueCount(getDemographicsProperty()) > 0;
    }

    public Iterator listDemographics() {
        return listPropertyValuesAs(getDemographicsProperty(), Get_Conditional_Data_Macro.class);
    }

    public void addDemographics(Get_Conditional_Data_Macro newDemographics) {
        addPropertyValue(getDemographicsProperty(), newDemographics);
    }

    public void removeDemographics(Get_Conditional_Data_Macro oldDemographics) {
        removePropertyValue(getDemographicsProperty(), oldDemographics);
    }

    public void setDemographics(Collection newDemographics) {
        setPropertyValues(getDemographicsProperty(), newDemographics);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
