package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Keyword_Didactic
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public class DefaultKeyword_Didactic extends DefaultSupplemental_Material implements Keyword_Didactic {
    public DefaultKeyword_Didactic() {}

    public DefaultKeyword_Didactic(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#keywords
    public Collection getKeywords() {
        return getPropertyValuesAs(getKeywordsProperty(), Concept.class);
    }

    public RDFProperty getKeywordsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#keywords";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasKeywords() {
        return getPropertyValueCount(getKeywordsProperty()) > 0;
    }

    public Iterator listKeywords() {
        return listPropertyValuesAs(getKeywordsProperty(), Concept.class);
    }

    public void addKeywords(Concept newKeywords) {
        addPropertyValue(getKeywordsProperty(), newKeywords);
    }

    public void removeKeywords(Concept oldKeywords) {
        removePropertyValue(getKeywordsProperty(), oldKeywords);
    }

    public void setKeywords(Collection newKeywords) {
        setPropertyValues(getKeywordsProperty(), newKeywords);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
