package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#User_Defined_Data_Model_Class
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public class DefaultUser_Defined_Data_Model_Class extends DefaultRDFIndividual
        implements User_Defined_Data_Model_Class {
    public DefaultUser_Defined_Data_Model_Class() {}

    public DefaultUser_Defined_Data_Model_Class(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
