package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Float_Value
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public class DefaultFloat_Value extends DefaultPrimitive_Data_Value implements Float_Value {
    public DefaultFloat_Value() {}

    public DefaultFloat_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#float_value
    public float getFloat_value() {
        return getPropertyValueLiteral(getFloat_valueProperty()).getFloat();
    }

    public RDFProperty getFloat_valueProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#float_value";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasFloat_value() {
        return getPropertyValueCount(getFloat_valueProperty()) > 0;
    }

    public void setFloat_value(float newFloat_value) {
        setPropertyValue(getFloat_valueProperty(), new Float(newFloat_value));
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
