package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Iteration_Specification
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public class DefaultIteration_Specification extends DefaultGuideline_Model_Entity implements Iteration_Specification {
    public DefaultIteration_Specification() {}

    public DefaultIteration_Specification(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#abort_condition
    public Criterion getAbort_condition() {
        return (Criterion) getPropertyValueAs(getAbort_conditionProperty(), Criterion.class);
    }

    public RDFProperty getAbort_conditionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#abort_condition";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAbort_condition() {
        return getPropertyValueCount(getAbort_conditionProperty()) > 0;
    }

    public void setAbort_condition(Criterion newAbort_condition) {
        setPropertyValue(getAbort_conditionProperty(), newAbort_condition);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#iteration_frequency
    public Iteration_Expression getIteration_frequency() {
        return (Iteration_Expression) getPropertyValueAs(getIteration_frequencyProperty(), Iteration_Expression.class);
    }

    public RDFProperty getIteration_frequencyProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#iteration_frequency";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasIteration_frequency() {
        return getPropertyValueCount(getIteration_frequencyProperty()) > 0;
    }

    public void setIteration_frequency(Iteration_Expression newIteration_frequency) {
        setPropertyValue(getIteration_frequencyProperty(), newIteration_frequency);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#stopping_condition
    public Criterion getStopping_condition() {
        return (Criterion) getPropertyValueAs(getStopping_conditionProperty(), Criterion.class);
    }

    public RDFProperty getStopping_conditionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#stopping_condition";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasStopping_condition() {
        return getPropertyValueCount(getStopping_conditionProperty()) > 0;
    }

    public void setStopping_condition(Criterion newStopping_condition) {
        setPropertyValue(getStopping_conditionProperty(), newStopping_condition);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
