package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Iteration_Expression
 *
 * @version generated on Thu Jun 08 17:29:55 EEST 2006
 */
public class DefaultIteration_Expression extends DefaultGuideline_Model_Entity implements Iteration_Expression {
    public DefaultIteration_Expression() {}

    public DefaultIteration_Expression(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
