package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Supplemental_Material_List
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public class DefaultSupplemental_Material_List extends DefaultGuideline_Model_Entity
        implements Supplemental_Material_List {
    public DefaultSupplemental_Material_List() {}

    public DefaultSupplemental_Material_List(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#items
    public Collection getItems() {
        return getPropertyValuesAs(getItemsProperty(), Supplemental_Material.class);
    }

    public RDFProperty getItemsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#items";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasItems() {
        return getPropertyValueCount(getItemsProperty()) > 0;
    }

    public Iterator listItems() {
        return listPropertyValuesAs(getItemsProperty(), Supplemental_Material.class);
    }

    public void addItems(Supplemental_Material newItems) {
        addPropertyValue(getItemsProperty(), newItems);
    }

    public void removeItems(Supplemental_Material oldItems) {
        removePropertyValue(getItemsProperty(), oldItems);
    }

    public void setItems(Collection newItems) {
        setPropertyValues(getItemsProperty(), newItems);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#purpose
    public String getPurpose() {
        return (String) getPropertyValue(getPurposeProperty());
    }

    public RDFProperty getPurposeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#purpose";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasPurpose() {
        return getPropertyValueCount(getPurposeProperty()) > 0;
    }

    public void setPurpose(String newPurpose) {
        setPropertyValue(getPurposeProperty(), newPurpose);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
