package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Strength_Of_Evidence_Or_Recommendation
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public class DefaultStrength_Of_Evidence_Or_Recommendation extends DefaultGLIF_Entity
        implements Strength_Of_Evidence_Or_Recommendation {
    public DefaultStrength_Of_Evidence_Or_Recommendation() {}

    public DefaultStrength_Of_Evidence_Or_Recommendation(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#coding_scheme
    public String getCoding_scheme() {
        return (String) getPropertyValue(getCoding_schemeProperty());
    }

    public RDFProperty getCoding_schemeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#coding_scheme";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCoding_scheme() {
        return getPropertyValueCount(getCoding_schemeProperty()) > 0;
    }

    public void setCoding_scheme(String newCoding_scheme) {
        setPropertyValue(getCoding_schemeProperty(), newCoding_scheme);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#strength
    public String getStrength() {
        return (String) getPropertyValue(getStrengthProperty());
    }

    public RDFProperty getStrengthProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#strength";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasStrength() {
        return getPropertyValueCount(getStrengthProperty()) > 0;
    }

    public void setStrength(String newStrength) {
        setPropertyValue(getStrengthProperty(), newStrength);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
