package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Fuzzy_Duration
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public class DefaultFuzzy_Duration extends DefaultGLIF_Entity implements Fuzzy_Duration {
    public DefaultFuzzy_Duration() {}

    public DefaultFuzzy_Duration(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#after_uncertainty
    public Duration getAfter_uncertainty() {
        return (Duration) getPropertyValueAs(getAfter_uncertaintyProperty(), Duration.class);
    }

    public RDFProperty getAfter_uncertaintyProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#after_uncertainty";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAfter_uncertainty() {
        return getPropertyValueCount(getAfter_uncertaintyProperty()) > 0;
    }

    public void setAfter_uncertainty(Duration newAfter_uncertainty) {
        setPropertyValue(getAfter_uncertaintyProperty(), newAfter_uncertainty);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#before_uncertainty
    public Duration getBefore_uncertainty() {
        return (Duration) getPropertyValueAs(getBefore_uncertaintyProperty(), Duration.class);
    }

    public RDFProperty getBefore_uncertaintyProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#before_uncertainty";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasBefore_uncertainty() {
        return getPropertyValueCount(getBefore_uncertaintyProperty()) > 0;
    }

    public void setBefore_uncertainty(Duration newBefore_uncertainty) {
        setPropertyValue(getBefore_uncertaintyProperty(), newBefore_uncertainty);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    public String getDisplay_name() {
        return (String) getPropertyValue(getDisplay_nameProperty());
    }

    public RDFProperty getDisplay_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#display_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDisplay_name() {
        return getPropertyValueCount(getDisplay_nameProperty()) > 0;
    }

    public void setDisplay_name(String newDisplay_name) {
        setPropertyValue(getDisplay_nameProperty(), newDisplay_name);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#duration
    public Duration getDuration() {
        return (Duration) getPropertyValueAs(getDurationProperty(), Duration.class);
    }

    public RDFProperty getDurationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#duration";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDuration() {
        return getPropertyValueCount(getDurationProperty()) > 0;
    }

    public void setDuration(Duration newDuration) {
        setPropertyValue(getDurationProperty(), newDuration);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
