package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Recommendations_Based_On_Risk
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public class DefaultRecommendations_Based_On_Risk extends DefaultMacro implements Recommendations_Based_On_Risk {
    public DefaultRecommendations_Based_On_Risk() {}

    public DefaultRecommendations_Based_On_Risk(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#condition
    public Criterion getCondition() {
        return (Criterion) getPropertyValueAs(getConditionProperty(), Criterion.class);
    }

    public RDFProperty getConditionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#condition";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCondition() {
        return getPropertyValueCount(getConditionProperty()) > 0;
    }

    public void setCondition(Criterion newCondition) {
        setPropertyValue(getConditionProperty(), newCondition);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#recommendation
    public Medically_Oriented_Action_Specification getRecommendation() {
        return (Medically_Oriented_Action_Specification) getPropertyValueAs(getRecommendationProperty(),
                Medically_Oriented_Action_Specification.class);
    }

    public RDFProperty getRecommendationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#recommendation";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasRecommendation() {
        return getPropertyValueCount(getRecommendationProperty()) > 0;
    }

    public void setRecommendation(Medically_Oriented_Action_Specification newRecommendation) {
        setPropertyValue(getRecommendationProperty(), newRecommendation);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
