package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Guideline
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public class DefaultGuideline extends DefaultNestable implements Guideline {
    public DefaultGuideline() {}

    public DefaultGuideline(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#algorithm
    public Algorithm getAlgorithm() {
        return (Algorithm) getPropertyValueAs(getAlgorithmProperty(), Algorithm.class);
    }

    public RDFProperty getAlgorithmProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#algorithm";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAlgorithm() {
        return getPropertyValueCount(getAlgorithmProperty()) > 0;
    }

    public void setAlgorithm(Algorithm newAlgorithm) {
        setPropertyValue(getAlgorithmProperty(), newAlgorithm);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#data_items
    public Data_Item_List getData_items() {
        return (Data_Item_List) getPropertyValueAs(getData_itemsProperty(), Data_Item_List.class);
    }

    public RDFProperty getData_itemsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#data_items";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasData_items() {
        return getPropertyValueCount(getData_itemsProperty()) > 0;
    }

    public void setData_items(Data_Item_List newData_items) {
        setPropertyValue(getData_itemsProperty(), newData_items);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#default_viewer
    public View_Specification getDefault_viewer() {
        return (View_Specification) getPropertyValueAs(getDefault_viewerProperty(), View_Specification.class);
    }

    public RDFProperty getDefault_viewerProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#default_viewer";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDefault_viewer() {
        return getPropertyValueCount(getDefault_viewerProperty()) > 0;
    }

    public void setDefault_viewer(View_Specification newDefault_viewer) {
        setPropertyValue(getDefault_viewerProperty(), newDefault_viewer);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#didactics
    public Collection getDidactics() {
        return getPropertyValuesAs(getDidacticsProperty(), Supplemental_Material_List.class);
    }

    public RDFProperty getDidacticsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#didactics";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDidactics() {
        return getPropertyValueCount(getDidacticsProperty()) > 0;
    }

    public Iterator listDidactics() {
        return listPropertyValuesAs(getDidacticsProperty(), Supplemental_Material_List.class);
    }

    public void addDidactics(Supplemental_Material_List newDidactics) {
        addPropertyValue(getDidacticsProperty(), newDidactics);
    }

    public void removeDidactics(Supplemental_Material_List oldDidactics) {
        removePropertyValue(getDidacticsProperty(), oldDidactics);
    }

    public void setDidactics(Collection newDidactics) {
        setPropertyValues(getDidacticsProperty(), newDidactics);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#eligibility_criteria
    public Collection getEligibility_criteria() {
        return getPropertyValuesAs(getEligibility_criteriaProperty(), Criterion.class);
    }

    public RDFProperty getEligibility_criteriaProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#eligibility_criteria";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEligibility_criteria() {
        return getPropertyValueCount(getEligibility_criteriaProperty()) > 0;
    }

    public Iterator listEligibility_criteria() {
        return listPropertyValuesAs(getEligibility_criteriaProperty(), Criterion.class);
    }

    public void addEligibility_criteria(Criterion newEligibility_criteria) {
        addPropertyValue(getEligibility_criteriaProperty(), newEligibility_criteria);
    }

    public void removeEligibility_criteria(Criterion oldEligibility_criteria) {
        removePropertyValue(getEligibility_criteriaProperty(), oldEligibility_criteria);
    }

    public void setEligibility_criteria(Collection newEligibility_criteria) {
        setPropertyValues(getEligibility_criteriaProperty(), newEligibility_criteria);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#exceptions
    public Collection getExceptions() {
        return getPropertyValuesAs(getExceptionsProperty(), Guideline_Exception.class);
    }

    public RDFProperty getExceptionsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#exceptions";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasExceptions() {
        return getPropertyValueCount(getExceptionsProperty()) > 0;
    }

    public Iterator listExceptions() {
        return listPropertyValuesAs(getExceptionsProperty(), Guideline_Exception.class);
    }

    public void addExceptions(Guideline_Exception newExceptions) {
        addPropertyValue(getExceptionsProperty(), newExceptions);
    }

    public void removeExceptions(Guideline_Exception oldExceptions) {
        removePropertyValue(getExceptionsProperty(), oldExceptions);
    }

    public void setExceptions(Collection newExceptions) {
        setPropertyValues(getExceptionsProperty(), newExceptions);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#intention
    public String getIntention() {
        return (String) getPropertyValue(getIntentionProperty());
    }

    public RDFProperty getIntentionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#intention";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasIntention() {
        return getPropertyValueCount(getIntentionProperty()) > 0;
    }

    public void setIntention(String newIntention) {
        setPropertyValue(getIntentionProperty(), newIntention);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#let_expressions
    public Collection getLet_expressions() {
        return getPropertyValuesAs(getLet_expressionsProperty(), Let_Expression.class);
    }

    public RDFProperty getLet_expressionsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#let_expressions";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasLet_expressions() {
        return getPropertyValueCount(getLet_expressionsProperty()) > 0;
    }

    public Iterator listLet_expressions() {
        return listPropertyValuesAs(getLet_expressionsProperty(), Let_Expression.class);
    }

    public void addLet_expressions(Let_Expression newLet_expressions) {
        addPropertyValue(getLet_expressionsProperty(), newLet_expressions);
    }

    public void removeLet_expressions(Let_Expression oldLet_expressions) {
        removePropertyValue(getLet_expressionsProperty(), oldLet_expressions);
    }

    public void setLet_expressions(Collection newLet_expressions) {
        setPropertyValues(getLet_expressionsProperty(), newLet_expressions);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#maintenance_info
    public Maintenance_Info getMaintenance_info() {
        return (Maintenance_Info) getPropertyValueAs(getMaintenance_infoProperty(), Maintenance_Info.class);
    }

    public RDFProperty getMaintenance_infoProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#maintenance_info";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMaintenance_info() {
        return getPropertyValueCount(getMaintenance_infoProperty()) > 0;
    }

    public void setMaintenance_info(Maintenance_Info newMaintenance_info) {
        setPropertyValue(getMaintenance_infoProperty(), newMaintenance_info);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#parameters_passed
    public Collection getParameters_passed() {
        return getPropertyValuesAs(getParameters_passedProperty(), Parameter_Passed.class);
    }

    public RDFProperty getParameters_passedProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#parameters_passed";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasParameters_passed() {
        return getPropertyValueCount(getParameters_passedProperty()) > 0;
    }

    public Iterator listParameters_passed() {
        return listPropertyValuesAs(getParameters_passedProperty(), Parameter_Passed.class);
    }

    public void addParameters_passed(Parameter_Passed newParameters_passed) {
        addPropertyValue(getParameters_passedProperty(), newParameters_passed);
    }

    public void removeParameters_passed(Parameter_Passed oldParameters_passed) {
        removePropertyValue(getParameters_passedProperty(), oldParameters_passed);
    }

    public void setParameters_passed(Collection newParameters_passed) {
        setPropertyValues(getParameters_passedProperty(), newParameters_passed);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
