package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Data_Item_List
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public class DefaultData_Item_List extends DefaultGuideline_Model_Entity implements Data_Item_List {
    public DefaultData_Item_List() {}

    public DefaultData_Item_List(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#entry_array
    public Collection getEntry_array() {
        return getPropertyValuesAs(getEntry_arrayProperty(), Data_Item.class);
    }

    public RDFProperty getEntry_arrayProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#entry_array";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEntry_array() {
        return getPropertyValueCount(getEntry_arrayProperty()) > 0;
    }

    public Iterator listEntry_array() {
        return listPropertyValuesAs(getEntry_arrayProperty(), Data_Item.class);
    }

    public void addEntry_array(Data_Item newEntry_array) {
        addPropertyValue(getEntry_arrayProperty(), newEntry_array);
    }

    public void removeEntry_array(Data_Item oldEntry_array) {
        removePropertyValue(getEntry_arrayProperty(), oldEntry_array);
    }

    public void setEntry_array(Collection newEntry_array) {
        setPropertyValues(getEntry_arrayProperty(), newEntry_array);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
