package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Every_Expression
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public class DefaultEvery_Expression extends DefaultFrequency_Expression implements Every_Expression {
    public DefaultEvery_Expression() {}

    public DefaultEvery_Expression(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#repeat_every
    public Fuzzy_Duration getRepeat_every() {
        return (Fuzzy_Duration) getPropertyValueAs(getRepeat_everyProperty(), Fuzzy_Duration.class);
    }

    public RDFProperty getRepeat_everyProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#repeat_every";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasRepeat_every() {
        return getPropertyValueCount(getRepeat_everyProperty()) > 0;
    }

    public void setRepeat_every(Fuzzy_Duration newRepeat_every) {
        setPropertyValue(getRepeat_everyProperty(), newRepeat_every);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#reset_iteration_points
    public boolean getReset_iteration_points() {
        return getPropertyValueLiteral(getReset_iteration_pointsProperty()).getBoolean();
    }

    public RDFProperty getReset_iteration_pointsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#reset_iteration_points";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasReset_iteration_points() {
        return getPropertyValueCount(getReset_iteration_pointsProperty()) > 0;
    }

    public void setReset_iteration_points(boolean newReset_iteration_points) {
        setPropertyValue(getReset_iteration_pointsProperty(), new Boolean(newReset_iteration_points));
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
