package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Duration_Value
 *
 * @version generated on Thu Jun 08 17:30:03 EEST 2006
 */
public class DefaultDuration_Value extends DefaultPrimitive_Data_Value implements Duration_Value {
    public DefaultDuration_Value() {}

    public DefaultDuration_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#duration_value
    public String getDuration_value() {
        return (String) getPropertyValue(getDuration_valueProperty());
    }

    public RDFProperty getDuration_valueProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#duration_value";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDuration_value() {
        return getPropertyValueCount(getDuration_valueProperty()) > 0;
    }

    public void setDuration_value(String newDuration_value) {
        setPropertyValue(getDuration_valueProperty(), newDuration_value);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
