package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Connector
 *
 * @version generated on Thu Jun 08 17:30:03 EEST 2006
 */
public class DefaultConnector extends DefaultDiagram_Entity implements Connector {
    public DefaultConnector() {}

    public DefaultConnector(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#first_object
    public Collection getFirst_object() {
        return getPropertyValues(getFirst_objectProperty());
    }

    public RDFProperty getFirst_objectProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#first_object";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasFirst_object() {
        return getPropertyValueCount(getFirst_objectProperty()) > 0;
    }

    public Iterator listFirst_object() {
        return listPropertyValues(getFirst_objectProperty());
    }

    public void addFirst_object(String newFirst_object) {
        addPropertyValue(getFirst_objectProperty(), newFirst_object);
    }

    public void removeFirst_object(String oldFirst_object) {
        removePropertyValue(getFirst_objectProperty(), oldFirst_object);
    }

    public void setFirst_object(Collection newFirst_object) {
        setPropertyValues(getFirst_objectProperty(), newFirst_object);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#second_object
    public Collection getSecond_object() {
        return getPropertyValues(getSecond_objectProperty());
    }

    public RDFProperty getSecond_objectProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#second_object";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasSecond_object() {
        return getPropertyValueCount(getSecond_objectProperty()) > 0;
    }

    public Iterator listSecond_object() {
        return listPropertyValues(getSecond_objectProperty());
    }

    public void addSecond_object(String newSecond_object) {
        addPropertyValue(getSecond_objectProperty(), newSecond_object);
    }

    public void removeSecond_object(String oldSecond_object) {
        removePropertyValue(getSecond_objectProperty(), oldSecond_object);
    }

    public void setSecond_object(Collection newSecond_object) {
        setPropertyValues(getSecond_objectProperty(), newSecond_object);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
