package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Maintenance_Info
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public class DefaultMaintenance_Info extends DefaultGLIF_Entity implements Maintenance_Info {
    public DefaultMaintenance_Info() {}

    public DefaultMaintenance_Info(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#GLIF_version
    public String getGLIF_version() {
        return (String) getPropertyValue(getGLIF_versionProperty());
    }

    public RDFProperty getGLIF_versionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#GLIF_version";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasGLIF_version() {
        return getPropertyValueCount(getGLIF_versionProperty()) > 0;
    }

    public void setGLIF_version(String newGLIF_version) {
        setPropertyValue(getGLIF_versionProperty(), newGLIF_version);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#adapting_institution
    public String getAdapting_institution() {
        return (String) getPropertyValue(getAdapting_institutionProperty());
    }

    public RDFProperty getAdapting_institutionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#adapting_institution";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAdapting_institution() {
        return getPropertyValueCount(getAdapting_institutionProperty()) > 0;
    }

    public void setAdapting_institution(String newAdapting_institution) {
        setPropertyValue(getAdapting_institutionProperty(), newAdapting_institution);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#author
    public Collection getAuthor() {
        return getPropertyValues(getAuthorProperty());
    }

    public RDFProperty getAuthorProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#author";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAuthor() {
        return getPropertyValueCount(getAuthorProperty()) > 0;
    }

    public Iterator listAuthor() {
        return listPropertyValues(getAuthorProperty());
    }

    public void addAuthor(String newAuthor) {
        addPropertyValue(getAuthorProperty(), newAuthor);
    }

    public void removeAuthor(String oldAuthor) {
        removePropertyValue(getAuthorProperty(), oldAuthor);
    }

    public void setAuthor(Collection newAuthor) {
        setPropertyValues(getAuthorProperty(), newAuthor);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#authoring_date
    public String getAuthoring_date() {
        return (String) getPropertyValue(getAuthoring_dateProperty());
    }

    public RDFProperty getAuthoring_dateProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#authoring_date";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAuthoring_date() {
        return getPropertyValueCount(getAuthoring_dateProperty()) > 0;
    }

    public void setAuthoring_date(String newAuthoring_date) {
        setPropertyValue(getAuthoring_dateProperty(), newAuthoring_date);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#developing_institution
    public Collection getDeveloping_institution() {
        return getPropertyValues(getDeveloping_institutionProperty());
    }

    public RDFProperty getDeveloping_institutionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#developing_institution";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDeveloping_institution() {
        return getPropertyValueCount(getDeveloping_institutionProperty()) > 0;
    }

    public Iterator listDeveloping_institution() {
        return listPropertyValues(getDeveloping_institutionProperty());
    }

    public void addDeveloping_institution(String newDeveloping_institution) {
        addPropertyValue(getDeveloping_institutionProperty(), newDeveloping_institution);
    }

    public void removeDeveloping_institution(String oldDeveloping_institution) {
        removePropertyValue(getDeveloping_institutionProperty(), oldDeveloping_institution);
    }

    public void setDeveloping_institution(Collection newDeveloping_institution) {
        setPropertyValues(getDeveloping_institutionProperty(), newDeveloping_institution);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#encoded_guideline_version
    public String getEncoded_guideline_version() {
        return (String) getPropertyValue(getEncoded_guideline_versionProperty());
    }

    public RDFProperty getEncoded_guideline_versionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#encoded_guideline_version";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEncoded_guideline_version() {
        return getPropertyValueCount(getEncoded_guideline_versionProperty()) > 0;
    }

    public void setEncoded_guideline_version(String newEncoded_guideline_version) {
        setPropertyValue(getEncoded_guideline_versionProperty(), newEncoded_guideline_version);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#encoded_last_modification_date
    public String getEncoded_last_modification_date() {
        return (String) getPropertyValue(getEncoded_last_modification_dateProperty());
    }

    public RDFProperty getEncoded_last_modification_dateProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#encoded_last_modification_date";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEncoded_last_modification_date() {
        return getPropertyValueCount(getEncoded_last_modification_dateProperty()) > 0;
    }

    public void setEncoded_last_modification_date(String newEncoded_last_modification_date) {
        setPropertyValue(getEncoded_last_modification_dateProperty(), newEncoded_last_modification_date);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#encoder
    public Collection getEncoder() {
        return getPropertyValues(getEncoderProperty());
    }

    public RDFProperty getEncoderProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#encoder";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEncoder() {
        return getPropertyValueCount(getEncoderProperty()) > 0;
    }

    public Iterator listEncoder() {
        return listPropertyValues(getEncoderProperty());
    }

    public void addEncoder(String newEncoder) {
        addPropertyValue(getEncoderProperty(), newEncoder);
    }

    public void removeEncoder(String oldEncoder) {
        removePropertyValue(getEncoderProperty(), oldEncoder);
    }

    public void setEncoder(Collection newEncoder) {
        setPropertyValues(getEncoderProperty(), newEncoder);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#guideline_status
    public String getGuideline_status() {
        return (String) getPropertyValue(getGuideline_statusProperty());
    }

    public RDFProperty getGuideline_statusProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#guideline_status";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasGuideline_status() {
        return getPropertyValueCount(getGuideline_statusProperty()) > 0;
    }

    public void setGuideline_status(String newGuideline_status) {
        setPropertyValue(getGuideline_statusProperty(), newGuideline_status);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#guideline_version
    public String getGuideline_version() {
        return (String) getPropertyValue(getGuideline_versionProperty());
    }

    public RDFProperty getGuideline_versionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#guideline_version";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasGuideline_version() {
        return getPropertyValueCount(getGuideline_versionProperty()) > 0;
    }

    public void setGuideline_version(String newGuideline_version) {
        setPropertyValue(getGuideline_versionProperty(), newGuideline_version);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#representation_status
    public String getRepresentation_status() {
        return (String) getPropertyValue(getRepresentation_statusProperty());
    }

    public RDFProperty getRepresentation_statusProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#representation_status";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasRepresentation_status() {
        return getPropertyValueCount(getRepresentation_statusProperty()) > 0;
    }

    public void setRepresentation_status(String newRepresentation_status) {
        setPropertyValue(getRepresentation_statusProperty(), newRepresentation_status);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#title
    public String getTitle() {
        return (String) getPropertyValue(getTitleProperty());
    }

    public RDFProperty getTitleProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#title";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasTitle() {
        return getPropertyValueCount(getTitleProperty()) > 0;
    }

    public void setTitle(String newTitle) {
        setPropertyValue(getTitleProperty(), newTitle);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
