package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Symbol_Value
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public class DefaultSymbol_Value extends DefaultPrimitive_Data_Value implements Symbol_Value {
    public DefaultSymbol_Value() {}

    public DefaultSymbol_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#symbol_value
    public String getSymbol_value() {
        return (String) getPropertyValue(getSymbol_valueProperty());
    }

    public RDFProperty getSymbol_valueProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#symbol_value";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasSymbol_value() {
        return getPropertyValueCount(getSymbol_valueProperty()) > 0;
    }

    public void setSymbol_value(String newSymbol_value) {
        setPropertyValue(getSymbol_valueProperty(), newSymbol_value);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
