//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.5-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.08.03 at 01:53:59 PM EEST 
//


package org.hl7.v3;

import javax.xml.bind.annotation.XmlEnum;


/**
 * <p>Java class for ActRelationshipPertains.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ActRelationshipPertains">
 *   &lt;restriction base="{urn:hl7-org:v3}cs">
 *     &lt;enumeration value="AUTH"/>
 *     &lt;enumeration value="CAUS"/>
 *     &lt;enumeration value="CHRG"/>
 *     &lt;enumeration value="COST"/>
 *     &lt;enumeration value="COVBY"/>
 *     &lt;enumeration value="CREDIT"/>
 *     &lt;enumeration value="DEBIT"/>
 *     &lt;enumeration value="DRIV"/>
 *     &lt;enumeration value="ELNK"/>
 *     &lt;enumeration value="EVID"/>
 *     &lt;enumeration value="EXPL"/>
 *     &lt;enumeration value="ITEMSLOC"/>
 *     &lt;enumeration value="LIMIT"/>
 *     &lt;enumeration value="MFST"/>
 *     &lt;enumeration value="NAME"/>
 *     &lt;enumeration value="PERT"/>
 *     &lt;enumeration value="PREV"/>
 *     &lt;enumeration value="REFR"/>
 *     &lt;enumeration value="REFV"/>
 *     &lt;enumeration value="SAE"/>
 *     &lt;enumeration value="SAS"/>
 *     &lt;enumeration value="SPRT"/>
 *     &lt;enumeration value="SPRTBND"/>
 *     &lt;enumeration value="SUBJ"/>
 *     &lt;enumeration value="SUMM"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlEnum
public enum ActRelationshipPertains {

    AUTH,
    CAUS,
    CHRG,
    COST,
    COVBY,
    CREDIT,
    DEBIT,
    DRIV,
    ELNK,
    EVID,
    EXPL,
    ITEMSLOC,
    LIMIT,
    MFST,
    NAME,
    PERT,
    PREV,
    REFR,
    REFV,
    SAE,
    SAS,
    SPRT,
    SPRTBND,
    SUBJ,
    SUMM;

    public String value() {
        return name();
    }

    public static ActRelationshipPertains fromValue(String v) {
        return valueOf(v);
    }

}
