package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Risk_Assessment_Macro
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public class DefaultRisk_Assessment_Macro extends DefaultMacro implements Risk_Assessment_Macro {
    public DefaultRisk_Assessment_Macro() {}

    public DefaultRisk_Assessment_Macro(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#calculation_data
    public Conditional_Data_List_Macro getCalculation_data() {
        return (Conditional_Data_List_Macro) getPropertyValueAs(getCalculation_dataProperty(),
                Conditional_Data_List_Macro.class);
    }

    public RDFProperty getCalculation_dataProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#calculation_data";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCalculation_data() {
        return getPropertyValueCount(getCalculation_dataProperty()) > 0;
    }

    public void setCalculation_data(Conditional_Data_List_Macro newCalculation_data) {
        setPropertyValue(getCalculation_dataProperty(), newCalculation_data);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#recommendations
    public Recommendations_Based_On_Risk getRecommendations() {
        return (Recommendations_Based_On_Risk) getPropertyValueAs(getRecommendationsProperty(),
                Recommendations_Based_On_Risk.class);
    }

    public RDFProperty getRecommendationsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#recommendations";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasRecommendations() {
        return getPropertyValueCount(getRecommendationsProperty()) > 0;
    }

    public void setRecommendations(Recommendations_Based_On_Risk newRecommendations) {
        setPropertyValue(getRecommendationsProperty(), newRecommendations);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#risk_calculation
    public Risk_Calculation_Macro getRisk_calculation() {
        return (Risk_Calculation_Macro) getPropertyValueAs(getRisk_calculationProperty(), Risk_Calculation_Macro.class);
    }

    public RDFProperty getRisk_calculationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#risk_calculation";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasRisk_calculation() {
        return getPropertyValueCount(getRisk_calculationProperty()) > 0;
    }

    public void setRisk_calculation(Risk_Calculation_Macro newRisk_calculation) {
        setPropertyValue(getRisk_calculationProperty(), newRisk_calculation);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
