package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Concept
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public class DefaultConcept extends DefaultKnowledge_Item implements Concept {
    public DefaultConcept() {}

    public DefaultConcept(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#concept_id
    public String getConcept_id() {
        return (String) getPropertyValue(getConcept_idProperty());
    }

    public RDFProperty getConcept_idProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#concept_id";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasConcept_id() {
        return getPropertyValueCount(getConcept_idProperty()) > 0;
    }

    public void setConcept_id(String newConcept_id) {
        setPropertyValue(getConcept_idProperty(), newConcept_id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#concept_name
    public String getConcept_name() {
        return (String) getPropertyValue(getConcept_nameProperty());
    }

    public RDFProperty getConcept_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#concept_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasConcept_name() {
        return getPropertyValueCount(getConcept_nameProperty()) > 0;
    }

    public void setConcept_name(String newConcept_name) {
        setPropertyValue(getConcept_nameProperty(), newConcept_name);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#concept_source
    public String getConcept_source() {
        return (String) getPropertyValue(getConcept_sourceProperty());
    }

    public RDFProperty getConcept_sourceProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#concept_source";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasConcept_source() {
        return getPropertyValueCount(getConcept_sourceProperty()) > 0;
    }

    public void setConcept_source(String newConcept_source) {
        setPropertyValue(getConcept_sourceProperty(), newConcept_source);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
