package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Guideline_Exception
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public class DefaultGuideline_Exception extends DefaultGLIF_Entity implements Guideline_Exception {
    public DefaultGuideline_Exception() {}

    public DefaultGuideline_Exception(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#condition
    public Criterion getCondition() {
        return (Criterion) getPropertyValueAs(getConditionProperty(), Criterion.class);
    }

    public RDFProperty getConditionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#condition";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCondition() {
        return getPropertyValueCount(getConditionProperty()) > 0;
    }

    public void setCondition(Criterion newCondition) {
        setPropertyValue(getConditionProperty(), newCondition);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#exception_event
    public Event getException_event() {
        return (Event) getPropertyValueAs(getException_eventProperty(), Event.class);
    }

    public RDFProperty getException_eventProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#exception_event";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasException_event() {
        return getPropertyValueCount(getException_eventProperty()) > 0;
    }

    public void setException_event(Event newException_event) {
        setPropertyValue(getException_eventProperty(), newException_event);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#next_step
    public Guideline_Step getNext_step() {
        return (Guideline_Step) getPropertyValueAs(getNext_stepProperty(), Guideline_Step.class);
    }

    public RDFProperty getNext_stepProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#next_step";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasNext_step() {
        return getPropertyValueCount(getNext_stepProperty()) > 0;
    }

    public void setNext_step(Guideline_Step newNext_step) {
        setPropertyValue(getNext_stepProperty(), newNext_step);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#priority
    public int getPriority() {
        return getPropertyValueLiteral(getPriorityProperty()).getInt();
    }

    public RDFProperty getPriorityProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#priority";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasPriority() {
        return getPropertyValueCount(getPriorityProperty()) > 0;
    }

    public void setPriority(int newPriority) {
        setPropertyValue(getPriorityProperty(), new Integer(newPriority));
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
