package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Event
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public class DefaultEvent extends DefaultGuideline_Model_Entity implements Event {
    public DefaultEvent() {}

    public DefaultEvent(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#event_type
    public String getEvent_type() {
        return (String) getPropertyValue(getEvent_typeProperty());
    }

    public RDFProperty getEvent_typeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#event_type";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasEvent_type() {
        return getPropertyValueCount(getEvent_typeProperty()) > 0;
    }

    public void setEvent_type(String newEvent_type) {
        setPropertyValue(getEvent_typeProperty(), newEvent_type);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
