package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Subguideline_Action
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public class DefaultSubguideline_Action extends DefaultProgramming_Oriented_Action_Specification
        implements Subguideline_Action {
    public DefaultSubguideline_Action() {}

    public DefaultSubguideline_Action(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#action_detail
    public Nestable getAction_detail() {
        return (Nestable) getPropertyValueAs(getAction_detailProperty(), Nestable.class);
    }

    public RDFProperty getAction_detailProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#action_detail";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAction_detail() {
        return getPropertyValueCount(getAction_detailProperty()) > 0;
    }

    public void setAction_detail(Nestable newAction_detail) {
        setPropertyValue(getAction_detailProperty(), newAction_detail);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
