package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Set_Value
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public class DefaultSet_Value extends DefaultPrimitive_Data_Value implements Set_Value {
    public DefaultSet_Value() {}

    public DefaultSet_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#set_value
    public Collection getSet_value() {
        return getPropertyValuesAs(getSet_valueProperty(), Basic_Data_Type.class);
    }

    public RDFProperty getSet_valueProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#set_value";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasSet_value() {
        return getPropertyValueCount(getSet_valueProperty()) > 0;
    }

    public Iterator listSet_value() {
        return listPropertyValuesAs(getSet_valueProperty(), Basic_Data_Type.class);
    }

    public void addSet_value(Basic_Data_Type newSet_value) {
        addPropertyValue(getSet_valueProperty(), newSet_value);
    }

    public void removeSet_value(Basic_Data_Type oldSet_value) {
        removePropertyValue(getSet_valueProperty(), oldSet_value);
    }

    public void setSet_value(Collection newSet_value) {
        setPropertyValues(getSet_valueProperty(), newSet_value);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
