package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Get_Data_Action
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public class DefaultGet_Data_Action extends DefaultProgramming_Oriented_Action_Specification
        implements Get_Data_Action {
    public DefaultGet_Data_Action() {}

    public DefaultGet_Data_Action(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#attribute_to_be_assigned
    public String getAttribute_to_be_assigned() {
        return (String) getPropertyValue(getAttribute_to_be_assignedProperty());
    }

    public RDFProperty getAttribute_to_be_assignedProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#attribute_to_be_assigned";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasAttribute_to_be_assigned() {
        return getPropertyValueCount(getAttribute_to_be_assignedProperty()) > 0;
    }

    public void setAttribute_to_be_assigned(String newAttribute_to_be_assigned) {
        setPropertyValue(getAttribute_to_be_assignedProperty(), newAttribute_to_be_assigned);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#data_item
    public Data_Item getData_item() {
        return (Data_Item) getPropertyValueAs(getData_itemProperty(), Data_Item.class);
    }

    public RDFProperty getData_itemProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#data_item";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasData_item() {
        return getPropertyValueCount(getData_itemProperty()) > 0;
    }

    public void setData_item(Data_Item newData_item) {
        setPropertyValue(getData_itemProperty(), newData_item);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#data_source_type
    public Data_Entity getData_source_type() {
        return (Data_Entity) getPropertyValueAs(getData_source_typeProperty(), Data_Entity.class);
    }

    public RDFProperty getData_source_typeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#data_source_type";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasData_source_type() {
        return getPropertyValueCount(getData_source_typeProperty()) > 0;
    }

    public void setData_source_type(Data_Entity newData_source_type) {
        setPropertyValue(getData_source_typeProperty(), newData_source_type);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#primary_time
    public String getPrimary_time() {
        return (String) getPropertyValue(getPrimary_timeProperty());
    }

    public RDFProperty getPrimary_timeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#primary_time";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasPrimary_time() {
        return getPropertyValueCount(getPrimary_timeProperty()) > 0;
    }

    public void setPrimary_time(String newPrimary_time) {
        setPropertyValue(getPrimary_timeProperty(), newPrimary_time);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#variable_name
    public String getVariable_name() {
        return (String) getPropertyValue(getVariable_nameProperty());
    }

    public RDFProperty getVariable_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#variable_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasVariable_name() {
        return getPropertyValueCount(getVariable_nameProperty()) > 0;
    }

    public void setVariable_name(String newVariable_name) {
        setPropertyValue(getVariable_nameProperty(), newVariable_name);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
