package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Variable_Data_Item
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public class DefaultVariable_Data_Item extends DefaultData_Item implements Variable_Data_Item {
    public DefaultVariable_Data_Item() {}

    public DefaultVariable_Data_Item(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#owner
    public String getOwner() {
        return (String) getPropertyValue(getOwnerProperty());
    }

    public RDFProperty getOwnerProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#owner";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasOwner() {
        return getPropertyValueCount(getOwnerProperty()) > 0;
    }

    public void setOwner(String newOwner) {
        setPropertyValue(getOwnerProperty(), newOwner);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
