package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Criterion
 *
 * @version generated on Tue Jul 04 17:06:50 EEST 2006
 */
public class DefaultCriterion extends DefaultGuideline_Expression implements Criterion {
    public DefaultCriterion() {}

    public DefaultCriterion(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#triggering_event
    public Event getTriggering_event() {
        return (Event) getPropertyValueAs(getTriggering_eventProperty(), Event.class);
    }

    public RDFProperty getTriggering_eventProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#triggering_event";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasTriggering_event() {
        return getPropertyValueCount(getTriggering_eventProperty()) > 0;
    }

    public void setTriggering_event(Event newTriggering_event) {
        setPropertyValue(getTriggering_eventProperty(), newTriggering_event);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
