package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Utility_Choice
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public class DefaultUtility_Choice extends DefaultChoice implements Utility_Choice {
    public DefaultUtility_Choice() {}

    public DefaultUtility_Choice(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#node
    public String getNode() {
        return (String) getPropertyValue(getNodeProperty());
    }

    public RDFProperty getNodeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#node";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasNode() {
        return getPropertyValueCount(getNodeProperty()) > 0;
    }

    public void setNode(String newNode) {
        setPropertyValue(getNodeProperty(), newNode);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
