package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Parameter_Passed
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public class DefaultParameter_Passed extends DefaultGuideline_Model_Entity implements Parameter_Passed {
    public DefaultParameter_Passed() {}

    public DefaultParameter_Passed(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#direction
    public String getDirection() {
        return (String) getPropertyValue(getDirectionProperty());
    }

    public RDFProperty getDirectionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#direction";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDirection() {
        return getPropertyValueCount(getDirectionProperty()) > 0;
    }

    public void setDirection(String newDirection) {
        setPropertyValue(getDirectionProperty(), newDirection);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#variable_data_item
    public Variable_Data_Item getVariable_data_item() {
        return (Variable_Data_Item) getPropertyValueAs(getVariable_data_itemProperty(), Variable_Data_Item.class);
    }

    public RDFProperty getVariable_data_itemProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#variable_data_item";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasVariable_data_item() {
        return getPropertyValueCount(getVariable_data_itemProperty()) > 0;
    }

    public void setVariable_data_item(Variable_Data_Item newVariable_data_item) {
        setPropertyValue(getVariable_data_itemProperty(), newVariable_data_item);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#variable_type
    public String getVariable_type() {
        return (String) getPropertyValue(getVariable_typeProperty());
    }

    public RDFProperty getVariable_typeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#variable_type";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasVariable_type() {
        return getPropertyValueCount(getVariable_typeProperty()) > 0;
    }

    public void setVariable_type(String newVariable_type) {
        setPropertyValue(getVariable_typeProperty(), newVariable_type);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
