package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#AttributeDescription
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public class DefaultAttributeDescription extends DefaultCore_GLIF_Class implements AttributeDescription {
    public DefaultAttributeDescription() {}

    public DefaultAttributeDescription(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#cardinality
    public String getCardinality() {
        return (String) getPropertyValue(getCardinalityProperty());
    }

    public RDFProperty getCardinalityProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#cardinality";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCardinality() {
        return getPropertyValueCount(getCardinalityProperty()) > 0;
    }

    public void setCardinality(String newCardinality) {
        setPropertyValue(getCardinalityProperty(), newCardinality);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#domain
    public Collection getDomain() {
        return getPropertyValuesAs(getDomainProperty(), Concept.class);
    }

    public RDFProperty getDomainProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#domain";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDomain() {
        return getPropertyValueCount(getDomainProperty()) > 0;
    }

    public Iterator listDomain() {
        return listPropertyValuesAs(getDomainProperty(), Concept.class);
    }

    public void addDomain(Concept newDomain) {
        addPropertyValue(getDomainProperty(), newDomain);
    }

    public void removeDomain(Concept oldDomain) {
        removePropertyValue(getDomainProperty(), oldDomain);
    }

    public void setDomain(Collection newDomain) {
        setPropertyValues(getDomainProperty(), newDomain);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#name2
    public String getName2() {
        return (String) getPropertyValue(getName2Property());
    }

    public RDFProperty getName2Property() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#name2";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasName2() {
        return getPropertyValueCount(getName2Property()) > 0;
    }

    public void setName2(String newName2) {
        setPropertyValue(getName2Property(), newName2);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
