package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Observation
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public class DefaultObservation extends DefaultPatient_Data implements Observation {
    public DefaultObservation() {}

    public DefaultObservation(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#certainty
    public int getCertainty() {
        return getPropertyValueLiteral(getCertaintyProperty()).getInt();
    }

    public RDFProperty getCertaintyProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#certainty";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasCertainty() {
        return getPropertyValueCount(getCertaintyProperty()) > 0;
    }

    public void setCertainty(int newCertainty) {
        setPropertyValue(getCertaintyProperty(), new Integer(newCertainty));
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#derivation_expression
    public String getDerivation_expression() {
        return (String) getPropertyValue(getDerivation_expressionProperty());
    }

    public RDFProperty getDerivation_expressionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#derivation_expression";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDerivation_expression() {
        return getPropertyValueCount(getDerivation_expressionProperty()) > 0;
    }

    public void setDerivation_expression(String newDerivation_expression) {
        setPropertyValue(getDerivation_expressionProperty(), newDerivation_expression);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#normal_range
    public Range getNormal_range() {
        return (Range) getPropertyValueAs(getNormal_rangeProperty(), Range.class);
    }

    public RDFProperty getNormal_rangeProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#normal_range";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasNormal_range() {
        return getPropertyValueCount(getNormal_rangeProperty()) > 0;
    }

    public void setNormal_range(Range newNormal_range) {
        setPropertyValue(getNormal_rangeProperty(), newNormal_range);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#severity
    public int getSeverity() {
        return getPropertyValueLiteral(getSeverityProperty()).getInt();
    }

    public RDFProperty getSeverityProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#severity";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasSeverity() {
        return getPropertyValueCount(getSeverityProperty()) > 0;
    }

    public void setSeverity(int newSeverity) {
        setPropertyValue(getSeverityProperty(), new Integer(newSeverity));
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#value
    public Observation_Value getValue() {
        return (Observation_Value) getPropertyValueAs(getValueProperty(), Observation_Value.class);
    }

    public RDFProperty getValueProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#value";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasValue() {
        return getPropertyValueCount(getValueProperty()) > 0;
    }

    public void setValue(Observation_Value newValue) {
        setPropertyValue(getValueProperty(), newValue);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
