package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Case_Step
 *
 * @version generated on Thu Jun 08 17:29:55 EEST 2006
 */
public class DefaultCase_Step extends DefaultDecision_Step implements Case_Step {
    public DefaultCase_Step() {}

    public DefaultCase_Step(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#default_next_step
    public Guideline_Step getDefault_next_step() {
        return (Guideline_Step) getPropertyValueAs(getDefault_next_stepProperty(), Guideline_Step.class);
    }

    public RDFProperty getDefault_next_stepProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#default_next_step";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasDefault_next_step() {
        return getPropertyValueCount(getDefault_next_stepProperty()) > 0;
    }

    public void setDefault_next_step(Guideline_Step newDefault_next_step) {
        setPropertyValue(getDefault_next_stepProperty(), newDefault_next_step);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#expression
    public Guideline_Expression getExpression() {
        return (Guideline_Expression) getPropertyValueAs(getExpressionProperty(), Guideline_Expression.class);
    }

    public RDFProperty getExpressionProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#expression";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasExpression() {
        return getPropertyValueCount(getExpressionProperty()) > 0;
    }

    public void setExpression(Guideline_Expression newExpression) {
        setPropertyValue(getExpressionProperty(), newExpression);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#operator
    public String getOperator() {
        return (String) getPropertyValue(getOperatorProperty());
    }

    public RDFProperty getOperatorProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#operator";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasOperator() {
        return getPropertyValueCount(getOperatorProperty()) > 0;
    }

    public void setOperator(String newOperator) {
        setPropertyValue(getOperatorProperty(), newOperator);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
