package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#ObjectLocation
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public class DefaultObjectLocation extends DefaultDiagram_Entity implements ObjectLocation {
    public DefaultObjectLocation() {}

    public DefaultObjectLocation(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#location
    public Collection getLocation() {
        return getPropertyValuesAs(getLocationProperty(), Rectangle.class);
    }

    public RDFProperty getLocationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#location";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasLocation() {
        return getPropertyValueCount(getLocationProperty()) > 0;
    }

    public Iterator listLocation() {
        return listPropertyValuesAs(getLocationProperty(), Rectangle.class);
    }

    public void addLocation(Rectangle newLocation) {
        addPropertyValue(getLocationProperty(), newLocation);
    }

    public void removeLocation(Rectangle oldLocation) {
        removePropertyValue(getLocationProperty(), oldLocation);
    }

    public void setLocation(Collection newLocation) {
        setPropertyValues(getLocationProperty(), newLocation);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#object
    public Collection getObject() {
        return getPropertyValues(getObjectProperty());
    }

    public RDFProperty getObjectProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#object";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasObject() {
        return getPropertyValueCount(getObjectProperty()) > 0;
    }

    public Iterator listObject() {
        return listPropertyValues(getObjectProperty());
    }

    public void addObject(Object newObject) {
        addPropertyValue(getObjectProperty(), newObject);
    }

    public void removeObject(Object oldObject) {
        removePropertyValue(getObjectProperty(), oldObject);
    }

    public void setObject(Collection newObject) {
        setPropertyValues(getObjectProperty(), newObject);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
