package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Compound_Data_Value
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public class DefaultCompound_Data_Value extends DefaultData_Value implements Compound_Data_Value {
    public DefaultCompound_Data_Value() {}

    public DefaultCompound_Data_Value(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#data_value_name
    public String getData_value_name() {
        return (String) getPropertyValue(getData_value_nameProperty());
    }

    public RDFProperty getData_value_nameProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#data_value_name";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasData_value_name() {
        return getPropertyValueCount(getData_value_nameProperty()) > 0;
    }

    public void setData_value_name(String newData_value_name) {
        setPropertyValue(getData_value_nameProperty(), newData_value_name);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#parameters
    public Collection getParameters() {
        return getPropertyValuesAs(getParametersProperty(), Parameter_Name_And_Value.class);
    }

    public RDFProperty getParametersProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#parameters";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasParameters() {
        return getPropertyValueCount(getParametersProperty()) > 0;
    }

    public Iterator listParameters() {
        return listPropertyValuesAs(getParametersProperty(), Parameter_Name_And_Value.class);
    }

    public void addParameters(Parameter_Name_And_Value newParameters) {
        addPropertyValue(getParametersProperty(), newParameters);
    }

    public void removeParameters(Parameter_Name_And_Value oldParameters) {
        removePropertyValue(getParametersProperty(), oldParameters);
    }

    public void setParameters(Collection newParameters) {
        setPropertyValues(getParametersProperty(), newParameters);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
