package tr.com.srdc.icardea.careplanengine.glmodel.impl;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protege.model.FrameID;
import edu.stanford.smi.protegex.owl.model.*;
import edu.stanford.smi.protegex.owl.model.impl.*;

import tr.com.srdc.icardea.careplanengine.glmodel.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Network
 *
 * @version generated on Thu Jun 08 17:30:03 EEST 2006
 */
public class DefaultNetwork extends DefaultDiagram_Entity implements Network {
    public DefaultNetwork() {}

    public DefaultNetwork(OWLModel owlModel, FrameID id) {
        super(owlModel, id);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#connectors
    public Collection getConnectors() {
        return getPropertyValuesAs(getConnectorsProperty(), Connector.class);
    }

    public RDFProperty getConnectorsProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#connectors";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasConnectors() {
        return getPropertyValueCount(getConnectorsProperty()) > 0;
    }

    public Iterator listConnectors() {
        return listPropertyValuesAs(getConnectorsProperty(), Connector.class);
    }

    public void addConnectors(Connector newConnectors) {
        addPropertyValue(getConnectorsProperty(), newConnectors);
    }

    public void removeConnectors(Connector oldConnectors) {
        removePropertyValue(getConnectorsProperty(), oldConnectors);
    }

    public void setConnectors(Collection newConnectors) {
        setPropertyValues(getConnectorsProperty(), newConnectors);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#last_divider_location
    public Collection getLast_divider_location() {
        return getPropertyValues(getLast_divider_locationProperty());
    }

    public RDFProperty getLast_divider_locationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#last_divider_location";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasLast_divider_location() {
        return getPropertyValueCount(getLast_divider_locationProperty()) > 0;
    }

    public Iterator listLast_divider_location() {
        return listPropertyValues(getLast_divider_locationProperty());
    }

    public void addLast_divider_location(int newLast_divider_location) {
        addPropertyValue(getLast_divider_locationProperty(), newLast_divider_location);
    }

    public void removeLast_divider_location(int oldLast_divider_location) {
        removePropertyValue(getLast_divider_locationProperty(), oldLast_divider_location);
    }

    public void setLast_divider_location(Collection newLast_divider_location) {
        setPropertyValues(getLast_divider_locationProperty(), newLast_divider_location);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#layout_information
    public Collection getLayout_information() {
        return getPropertyValuesAs(getLayout_informationProperty(), ObjectLocation.class);
    }

    public RDFProperty getLayout_informationProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#layout_information";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasLayout_information() {
        return getPropertyValueCount(getLayout_informationProperty()) > 0;
    }

    public Iterator listLayout_information() {
        return listPropertyValuesAs(getLayout_informationProperty(), ObjectLocation.class);
    }

    public void addLayout_information(ObjectLocation newLayout_information) {
        addPropertyValue(getLayout_informationProperty(), newLayout_information);
    }

    public void removeLayout_information(ObjectLocation oldLayout_information) {
        removePropertyValue(getLayout_informationProperty(), oldLayout_information);
    }

    public void setLayout_information(Collection newLayout_information) {
        setPropertyValues(getLayout_informationProperty(), newLayout_information);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#main_panel_height
    public Collection getMain_panel_height() {
        return getPropertyValues(getMain_panel_heightProperty());
    }

    public RDFProperty getMain_panel_heightProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#main_panel_height";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMain_panel_height() {
        return getPropertyValueCount(getMain_panel_heightProperty()) > 0;
    }

    public Iterator listMain_panel_height() {
        return listPropertyValues(getMain_panel_heightProperty());
    }

    public void addMain_panel_height(int newMain_panel_height) {
        addPropertyValue(getMain_panel_heightProperty(), newMain_panel_height);
    }

    public void removeMain_panel_height(int oldMain_panel_height) {
        removePropertyValue(getMain_panel_heightProperty(), oldMain_panel_height);
    }

    public void setMain_panel_height(Collection newMain_panel_height) {
        setPropertyValues(getMain_panel_heightProperty(), newMain_panel_height);
    }

    // Property http://www.owl-ontologies.com/unnamed.owl#main_panel_width
    public Collection getMain_panel_width() {
        return getPropertyValues(getMain_panel_widthProperty());
    }

    public RDFProperty getMain_panel_widthProperty() {
        final String uri  = "http://www.owl-ontologies.com/unnamed.owl#main_panel_width";
        final String name = getOWLModel().getResourceNameForURI(uri);

        return getOWLModel().getRDFProperty(name);
    }

    public boolean hasMain_panel_width() {
        return getPropertyValueCount(getMain_panel_widthProperty()) > 0;
    }

    public Iterator listMain_panel_width() {
        return listPropertyValues(getMain_panel_widthProperty());
    }

    public void addMain_panel_width(int newMain_panel_width) {
        addPropertyValue(getMain_panel_widthProperty(), newMain_panel_width);
    }

    public void removeMain_panel_width(int oldMain_panel_width) {
        removePropertyValue(getMain_panel_widthProperty(), oldMain_panel_width);
    }

    public void setMain_panel_width(Collection newMain_panel_width) {
        setPropertyValues(getMain_panel_widthProperty(), newMain_panel_width);
    }
}


//~ Formatted by Jindent --- http://www.jindent.com
