//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.08 at 11:29:54 AM EEST 
//


package tr.com.srdc.icardea.careplanengine.xmlmodel;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Algorithm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Algorithm">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="StartStep" type="{}StartStep"/>
 *         &lt;element name="FinalStep" type="{}FinalStep"/>
 *         &lt;element name="DecisionStep" type="{}DecisionStep"/>
 *         &lt;element name="RecommendationStep" type="{}RecommendationStep"/>
 *         &lt;element name="ConsultStep" type="{}ConsultStep"/>
 *         &lt;element name="WaitStep" type="{}WaitStep"/>
 *         &lt;element name="RecordActionStep" type="{}RecordActionStep"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Algorithm", propOrder = {
    "startStepOrFinalStepOrDecisionStep"
})
public class Algorithm {

    @XmlElements({
        @XmlElement(name = "StartStep", type = StartStep.class),
        @XmlElement(name = "FinalStep", type = FinalStep.class),
        @XmlElement(name = "DecisionStep", type = DecisionStep.class),
        @XmlElement(name = "RecommendationStep", type = RecommendationStep.class),
        @XmlElement(name = "ConsultStep", type = ConsultStep.class),
        @XmlElement(name = "WaitStep", type = WaitStep.class),
        @XmlElement(name = "RecordActionStep", type = RecordActionStep.class)
    })
    protected List<Object> startStepOrFinalStepOrDecisionStep;

    /**
     * Gets the value of the startStepOrFinalStepOrDecisionStep property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the startStepOrFinalStepOrDecisionStep property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStartStepOrFinalStepOrDecisionStep().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StartStep }
     * {@link FinalStep }
     * {@link DecisionStep }
     * {@link RecommendationStep }
     * {@link ConsultStep }
     * {@link WaitStep }
     * {@link RecordActionStep }
     * 
     * 
     */
    public List<Object> getStartStepOrFinalStepOrDecisionStep() {
        if (startStepOrFinalStepOrDecisionStep == null) {
            startStepOrFinalStepOrDecisionStep = new ArrayList<Object>();
        }
        return this.startStepOrFinalStepOrDecisionStep;
    }

}
