//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.08 at 11:29:54 AM EEST 
//


package tr.com.srdc.icardea.careplanengine.xmlmodel;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Body complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Body">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EligibilityCriteria" type="{}EligibilityCriteria"/>
 *         &lt;element name="Algorithm" type="{}Algorithm" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Body", propOrder = {
    "eligibilityCriteria",
    "algorithm"
})
public class Body {

    @XmlElement(name = "EligibilityCriteria", required = true)
    protected EligibilityCriteria eligibilityCriteria;
    @XmlElement(name = "Algorithm")
    protected Algorithm algorithm;

    /**
     * Gets the value of the eligibilityCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link EligibilityCriteria }
     *     
     */
    public EligibilityCriteria getEligibilityCriteria() {
        return eligibilityCriteria;
    }

    /**
     * Sets the value of the eligibilityCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link EligibilityCriteria }
     *     
     */
    public void setEligibilityCriteria(EligibilityCriteria value) {
        this.eligibilityCriteria = value;
    }

    /**
     * Gets the value of the algorithm property.
     * 
     * @return
     *     possible object is
     *     {@link Algorithm }
     *     
     */
    public Algorithm getAlgorithm() {
        return algorithm;
    }

    /**
     * Sets the value of the algorithm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Algorithm }
     *     
     */
    public void setAlgorithm(Algorithm value) {
        this.algorithm = value;
    }

}
