package de.offis.health.icardea.cied.datamodel;

/**
 * TODO: Describe what this data model class stores for further processing
 * 
 * @author MYang
 */
public class CIEDDeviceData {
	private String mdc_IDC_MSMT_BATTERY_VOLTAGE=null;
	private String mdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE=null;
	private String mdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE=null;
	private String mdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE=null;
	private String mdc_IDC_MSMT_LEADHVCHNL_STATUS=null;  
	private String mdc_IDC_LEAD_CONNECTION_STATUS=null;
	/**
	 * @return the mdc_IDC_MSMT_BATTERY_VOLTAGE
	 */
	public String getMdc_IDC_MSMT_BATTERY_VOLTAGE() {
		return mdc_IDC_MSMT_BATTERY_VOLTAGE;
	}
	/**
	 * @param mdcIDCMSMTBATTERYVOLTAGE the mdc_IDC_MSMT_BATTERY_VOLTAGE to set
	 */
	public void setMdc_IDC_MSMT_BATTERY_VOLTAGE(String mdcIDCMSMTBATTERYVOLTAGE) {
		mdc_IDC_MSMT_BATTERY_VOLTAGE = mdcIDCMSMTBATTERYVOLTAGE;
	}
	/**
	 * @return the mdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE
	 */
	public String getMdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE() {
		return mdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE;
	}
	/**
	 * @param mdcIDCSETLEADCHNLRAPACINGAMPLITUDE the mdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE to set
	 */
	public void setMdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE(
			String mdcIDCSETLEADCHNLRAPACINGAMPLITUDE) {
		mdc_IDC_SET_LEADCHNL_RA_PACING_AMPLITUDE = mdcIDCSETLEADCHNLRAPACINGAMPLITUDE;
	}
	/**
	 * @return the mdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE
	 */
	public String getMdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE() {
		return mdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE;
	}
	/**
	 * @param mdcIDCSETLEADCHNLRVPACINGAMPLITUDE the mdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE to set
	 */
	public void setMdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE(
			String mdcIDCSETLEADCHNLRVPACINGAMPLITUDE) {
		mdc_IDC_SET_LEADCHNL_RV_PACING_AMPLITUDE = mdcIDCSETLEADCHNLRVPACINGAMPLITUDE;
	}
	/**
	 * @return the mdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE
	 */
	public String getMdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE() {
		return mdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE;
	}
	/**
	 * @param mdcIDCSETLEADCHNLLVPACINGAMPLITUDE the mdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE to set
	 */
	public void setMdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE(
			String mdcIDCSETLEADCHNLLVPACINGAMPLITUDE) {
		mdc_IDC_SET_LEADCHNL_LV_PACING_AMPLITUDE = mdcIDCSETLEADCHNLLVPACINGAMPLITUDE;
	}
	/**
	 * @return the mdc_IDC_MSMT_LEADHVCHNL_STATUS
	 */
	public String getMdc_IDC_MSMT_LEADHVCHNL_STATUS() {
		return mdc_IDC_MSMT_LEADHVCHNL_STATUS;
	}
	/**
	 * @param mdcIDCMSMTLEADHVCHNLSTATUS the mdc_IDC_MSMT_LEADHVCHNL_STATUS to set
	 */
	public void setMdc_IDC_MSMT_LEADHVCHNL_STATUS(String mdcIDCMSMTLEADHVCHNLSTATUS) {
		mdc_IDC_MSMT_LEADHVCHNL_STATUS = mdcIDCMSMTLEADHVCHNLSTATUS;
	}
	/**
	 * @return the mdc_IDC_LEAD_CONNECTION_STATUS
	 */
	public String getMdc_IDC_LEAD_CONNECTION_STATUS() {
		return mdc_IDC_LEAD_CONNECTION_STATUS;
	}
	/**
	 * @param mdcIDCLEADCONNECTIONSTATUS the mdc_IDC_LEAD_CONNECTION_STATUS to set
	 */
	public void setMdc_IDC_LEAD_CONNECTION_STATUS(String mdcIDCLEADCONNECTIONSTATUS) {
		mdc_IDC_LEAD_CONNECTION_STATUS = mdcIDCLEADCONNECTIONSTATUS;
	}
	
}