package de.offis.health.icardea.cied.datamodel;

/**
 * TODO: Describe what this data model class stores for further processing
 * 
 * @author MYang
 */
public class CIEDVTData {
	private String mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT=null;
	private String mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT=null;
	private String mdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT=null;
	private String mdc_IDC_EPISODE_TYPE_VT=null;
	/**
	 * @return the mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT
	 */
	public String getMdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT() {
		return mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT;
	}
	/**
	 * @param mdcIDCSTATTACHYTHERAPYSHOCKSDELIVEREDRECENT the mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT to set
	 */
	public void setMdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT(
			String mdcIDCSTATTACHYTHERAPYSHOCKSDELIVEREDRECENT) {
		mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_DELIVERED_RECENT = mdcIDCSTATTACHYTHERAPYSHOCKSDELIVEREDRECENT;
	}
	/**
	 * @return the mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT
	 */
	public String getMdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT() {
		return mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT;
	}
	/**
	 * @param mdcIDCSTATTACHYTHERAPYSHOCKSABORTEDRECENT the mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT to set
	 */
	public void setMdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT(
			String mdcIDCSTATTACHYTHERAPYSHOCKSABORTEDRECENT) {
		mdc_IDC_STAT_TACHYTHERAPY_SHOCKS_ABORTED_RECENT = mdcIDCSTATTACHYTHERAPYSHOCKSABORTEDRECENT;
	}
	/**
	 * @return the mdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT
	 */
	public String getMdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT() {
		return mdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT;
	}
	/**
	 * @param mdcIDCSTATTACHYTHERAPYATPDELIVEREDRECENT the mdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT to set
	 */
	public void setMdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT(
			String mdcIDCSTATTACHYTHERAPYATPDELIVEREDRECENT) {
		mdc_IDC_STAT_TACHYTHERAPY_ATP_DELIVERED_RECENT = mdcIDCSTATTACHYTHERAPYATPDELIVEREDRECENT;
	}
	/**
	 * @return the mdc_IDC_EPISODE_TYPE_VT
	 */
	public String getMdc_IDC_EPISODE_TYPE_VT() {
		return mdc_IDC_EPISODE_TYPE_VT;
	}
	/**
	 * @param mdcIDCEPISODETYPEVT the mdc_IDC_EPISODE_TYPE_VT to set
	 */
	public void setMdc_IDC_EPISODE_TYPE_VT(String mdcIDCEPISODETYPEVT) {
		mdc_IDC_EPISODE_TYPE_VT = mdcIDCEPISODETYPEVT;
	}
}