package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Action_Specification
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Action_Specification extends Guideline_Model_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#description
    String getDescription();

    RDFProperty getDescriptionProperty();

    boolean hasDescription();

    void setDescription(String newDescription);

    // Property http://www.owl-ontologies.com/unnamed.owl#intention
    String getIntention();

    RDFProperty getIntentionProperty();

    boolean hasIntention();

    void setIntention(String newIntention);
}


//~ Formatted by Jindent --- http://www.jindent.com
