package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Action_Step
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface Action_Step extends Guideline_Step {

    // Property http://www.owl-ontologies.com/unnamed.owl#duration_constraint
    Duration_Interval getDuration_constraint();

    RDFProperty getDuration_constraintProperty();

    boolean hasDuration_constraint();

    void setDuration_constraint(Duration_Interval newDuration_constraint);

    // Property http://www.owl-ontologies.com/unnamed.owl#exceptions
    Collection getExceptions();

    RDFProperty getExceptionsProperty();

    boolean hasExceptions();

    Iterator listExceptions();

    void addExceptions(Guideline_Exception newExceptions);

    void removeExceptions(Guideline_Exception oldExceptions);

    void setExceptions(Collection newExceptions);

    // Property http://www.owl-ontologies.com/unnamed.owl#iteration_info
    Iteration_Specification getIteration_info();

    RDFProperty getIteration_infoProperty();

    boolean hasIteration_info();

    void setIteration_info(Iteration_Specification newIteration_info);

    // Property http://www.owl-ontologies.com/unnamed.owl#next_step
    Guideline_Step getNext_step();

    RDFProperty getNext_stepProperty();

    boolean hasNext_step();

    void setNext_step(Guideline_Step newNext_step);

    // Property http://www.owl-ontologies.com/unnamed.owl#strength_of_recommendation
    Strength_Of_Evidence_Or_Recommendation getStrength_of_recommendation();

    RDFProperty getStrength_of_recommendationProperty();

    boolean hasStrength_of_recommendation();

    void setStrength_of_recommendation(Strength_Of_Evidence_Or_Recommendation newStrength_of_recommendation);

    // Property http://www.owl-ontologies.com/unnamed.owl#tasks
    Collection getTasks();

    RDFProperty getTasksProperty();

    boolean hasTasks();

    Iterator listTasks();

    void addTasks(Action_Specification newTasks);

    void removeTasks(Action_Specification oldTasks);

    void setTasks(Collection newTasks);

    // Property http://www.owl-ontologies.com/unnamed.owl#triggering_events
    Collection getTriggering_events();

    RDFProperty getTriggering_eventsProperty();

    boolean hasTriggering_events();

    Iterator listTriggering_events();

    void addTriggering_events(Triggering_Event newTriggering_events);

    void removeTriggering_events(Triggering_Event oldTriggering_events);

    void setTriggering_events(Collection newTriggering_events);
}


//~ Formatted by Jindent --- http://www.jindent.com
