package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Assignment_Action
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface Assignment_Action extends Programming_Oriented_Action_Specification {

    // Property http://www.owl-ontologies.com/unnamed.owl#expression
    Guideline_Expression getExpression();

    RDFProperty getExpressionProperty();

    boolean hasExpression();

    void setExpression(Guideline_Expression newExpression);

    // Property http://www.owl-ontologies.com/unnamed.owl#primitive_data_item_name
    String getPrimitive_data_item_name();

    RDFProperty getPrimitive_data_item_nameProperty();

    boolean hasPrimitive_data_item_name();

    void setPrimitive_data_item_name(String newPrimitive_data_item_name);
}


//~ Formatted by Jindent --- http://www.jindent.com
