package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Case_Condition
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface Case_Condition extends Decision_Condition {

    // Property http://www.owl-ontologies.com/unnamed.owl#case_value
    Guideline_Expression getCase_value();

    RDFProperty getCase_valueProperty();

    boolean hasCase_value();

    void setCase_value(Guideline_Expression newCase_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
