package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Compound_Data_Value
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Compound_Data_Value extends Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#data_value_name
    String getData_value_name();

    RDFProperty getData_value_nameProperty();

    boolean hasData_value_name();

    void setData_value_name(String newData_value_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#parameters
    Collection getParameters();

    RDFProperty getParametersProperty();

    boolean hasParameters();

    Iterator listParameters();

    void addParameters(Parameter_Name_And_Value newParameters);

    void removeParameters(Parameter_Name_And_Value oldParameters);

    void setParameters(Collection newParameters);
}


//~ Formatted by Jindent --- http://www.jindent.com
