package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Concept
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Concept extends Knowledge_Item {

    // Property http://www.owl-ontologies.com/unnamed.owl#concept_id
    String getConcept_id();

    RDFProperty getConcept_idProperty();

    boolean hasConcept_id();

    void setConcept_id(String newConcept_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#concept_name
    String getConcept_name();

    RDFProperty getConcept_nameProperty();

    boolean hasConcept_name();

    void setConcept_name(String newConcept_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#concept_source
    String getConcept_source();

    RDFProperty getConcept_sourceProperty();

    boolean hasConcept_source();

    void setConcept_source(String newConcept_source);
}


//~ Formatted by Jindent --- http://www.jindent.com
