package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#ConceptAttribute
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface ConceptAttribute extends AttributeDescription {

    // Property http://www.owl-ontologies.com/unnamed.owl#concept
    Concept getConcept();

    RDFProperty getConceptProperty();

    boolean hasConcept();

    void setConcept(Concept newConcept);
}


//~ Formatted by Jindent --- http://www.jindent.com
