package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Data_Item
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Data_Item extends Basic_Data_Type {

    // Property http://www.owl-ontologies.com/unnamed.owl#concept
    Concept getConcept();

    RDFProperty getConceptProperty();

    boolean hasConcept();

    void setConcept(Concept newConcept);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_model_class_id
    String getData_model_class_id();

    RDFProperty getData_model_class_idProperty();

    boolean hasData_model_class_id();

    void setData_model_class_id(String newData_model_class_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_model_source_id
    String getData_model_source_id();

    RDFProperty getData_model_source_idProperty();

    boolean hasData_model_source_id();

    void setData_model_source_id(String newData_model_source_id);

    // Property http://www.owl-ontologies.com/unnamed.owl#data_value
    Data_Item_Value getData_value();

    RDFProperty getData_valueProperty();

    boolean hasData_value();

    void setData_value(Data_Item_Value newData_value);

    // Property http://www.owl-ontologies.com/unnamed.owl#name2
    String getName2();

    RDFProperty getName2Property();

    boolean hasName2();

    void setName2(String newName2);
}


//~ Formatted by Jindent --- http://www.jindent.com
