package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Data_Value
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface Data_Value extends User_Defined_Data_Model_Class {

    // Property http://www.owl-ontologies.com/unnamed.owl#name2
    String getName2();

    RDFProperty getName2Property();

    boolean hasName2();

    void setName2(String newName2);
}


//~ Formatted by Jindent --- http://www.jindent.com
