package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Decision_Destinations
 *
 * @version generated on Thu Jun 08 17:30:01 EEST 2006
 */
public interface Decision_Destinations extends GLIF_connector {}


//~ Formatted by Jindent --- http://www.jindent.com
