package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Duration_Value
 *
 * @version generated on Thu Jun 08 17:30:03 EEST 2006
 */
public interface Duration_Value extends Primitive_Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#duration_value
    String getDuration_value();

    RDFProperty getDuration_valueProperty();

    boolean hasDuration_value();

    void setDuration_value(String newDuration_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
