package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Every_Expression
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Every_Expression extends Frequency_Expression {

    // Property http://www.owl-ontologies.com/unnamed.owl#repeat_every
    Fuzzy_Duration getRepeat_every();

    RDFProperty getRepeat_everyProperty();

    boolean hasRepeat_every();

    void setRepeat_every(Fuzzy_Duration newRepeat_every);

    // Property http://www.owl-ontologies.com/unnamed.owl#reset_iteration_points
    boolean getReset_iteration_points();

    RDFProperty getReset_iteration_pointsProperty();

    boolean hasReset_iteration_points();

    void setReset_iteration_points(boolean newReset_iteration_points);
}


//~ Formatted by Jindent --- http://www.jindent.com
