package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Frequency_Expression
 *
 * @version generated on Thu Jun 08 17:29:55 EEST 2006
 */
public interface Frequency_Expression extends Iteration_Expression {

    // Property http://www.owl-ontologies.com/unnamed.owl#for_
    Duration getFor_();

    RDFProperty getFor_Property();

    boolean hasFor_();

    void setFor_(Duration newFor_);
}


//~ Formatted by Jindent --- http://www.jindent.com
