package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

//~--- JDK imports ------------------------------------------------------------

import java.util.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Get_Knowledge_Action
 *
 * @version generated on Thu Jun 08 17:30:00 EEST 2006
 */
public interface Get_Knowledge_Action extends Programming_Oriented_Action_Specification {

    // Property http://www.owl-ontologies.com/unnamed.owl#input_relationships
    Collection getInput_relationships();

    RDFProperty getInput_relationshipsProperty();

    boolean hasInput_relationships();

    Iterator listInput_relationships();

    void addInput_relationships(Knowledge_Item newInput_relationships);

    void removeInput_relationships(Knowledge_Item oldInput_relationships);

    void setInput_relationships(Collection newInput_relationships);

    // Property http://www.owl-ontologies.com/unnamed.owl#variable_name
    String getVariable_name();

    RDFProperty getVariable_nameProperty();

    boolean hasVariable_name();

    void setVariable_name(String newVariable_name);
}


//~ Formatted by Jindent --- http://www.jindent.com
