package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Guideline_Duration_Expression
 *
 * @version generated on Thu Jun 08 17:29:56 EEST 2006
 */
public interface Guideline_Duration_Expression extends Duration {}


//~ Formatted by Jindent --- http://www.jindent.com
