package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Let_Expression
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Let_Expression extends Guideline_Model_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#expression_string
    String getExpression_string();

    RDFProperty getExpression_stringProperty();

    boolean hasExpression_string();

    void setExpression_string(String newExpression_string);

    // Property http://www.owl-ontologies.com/unnamed.owl#identifier
    String getIdentifier();

    RDFProperty getIdentifierProperty();

    boolean hasIdentifier();

    void setIdentifier(String newIdentifier);
}


//~ Formatted by Jindent --- http://www.jindent.com
