package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Material_URL
 *
 * @version generated on Thu Jun 08 17:30:02 EEST 2006
 */
public interface Material_URL extends Supplemental_Material {

    // Property http://www.owl-ontologies.com/unnamed.owl#url
    String getUrl();

    RDFProperty getUrlProperty();

    boolean hasUrl();

    void setUrl(String newUrl);
}


//~ Formatted by Jindent --- http://www.jindent.com
