package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Strength_Of_Evidence_Or_Recommendation
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface Strength_Of_Evidence_Or_Recommendation extends GLIF_Entity {

    // Property http://www.owl-ontologies.com/unnamed.owl#coding_scheme
    String getCoding_scheme();

    RDFProperty getCoding_schemeProperty();

    boolean hasCoding_scheme();

    void setCoding_scheme(String newCoding_scheme);

    // Property http://www.owl-ontologies.com/unnamed.owl#strength
    String getStrength();

    RDFProperty getStrengthProperty();

    boolean hasStrength();

    void setStrength(String newStrength);
}


//~ Formatted by Jindent --- http://www.jindent.com
