package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#String_Value
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface String_Value extends Primitive_Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#string_value
    String getString_value();

    RDFProperty getString_valueProperty();

    boolean hasString_value();

    void setString_value(String newString_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
