package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Symbol_Value
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface Symbol_Value extends Primitive_Data_Value {

    // Property http://www.owl-ontologies.com/unnamed.owl#symbol_value
    String getSymbol_value();

    RDFProperty getSymbol_valueProperty();

    boolean hasSymbol_value();

    void setSymbol_value(String newSymbol_value);
}


//~ Formatted by Jindent --- http://www.jindent.com
