package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Three_Valued_Criterion
 *
 * @version generated on Thu Jun 08 17:29:57 EEST 2006
 */
public interface Three_Valued_Criterion extends Criterion {}


//~ Formatted by Jindent --- http://www.jindent.com
