package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Time_Interval
 *
 * @version generated on Thu Jun 08 17:29:59 EEST 2006
 */
public interface Time_Interval extends Global_Concepts {

    // Property http://www.owl-ontologies.com/unnamed.owl#display_name
    String getDisplay_name();

    RDFProperty getDisplay_nameProperty();

    boolean hasDisplay_name();

    void setDisplay_name(String newDisplay_name);

    // Property http://www.owl-ontologies.com/unnamed.owl#max_time_stamp
    Time_Literal getMax_time_stamp();

    RDFProperty getMax_time_stampProperty();

    boolean hasMax_time_stamp();

    void setMax_time_stamp(Time_Literal newMax_time_stamp);

    // Property http://www.owl-ontologies.com/unnamed.owl#min_time_stamp
    Time_Literal getMin_time_stamp();

    RDFProperty getMin_time_stampProperty();

    boolean hasMin_time_stamp();

    void setMin_time_stamp(Time_Literal newMin_time_stamp);
}


//~ Formatted by Jindent --- http://www.jindent.com
