package tr.com.srdc.icardea.careplanengine.glmodel;

//~--- non-JDK imports --------------------------------------------------------

import edu.stanford.smi.protegex.owl.model.*;

/**
 * Generated by Protege-OWL  (http://protege.stanford.edu/plugins/owl).
 * Source OWL Class: http://www.owl-ontologies.com/unnamed.owl#Variable_Data_Item
 *
 * @version generated on Thu Jun 08 17:29:58 EEST 2006
 */
public interface Variable_Data_Item extends Data_Item {

    // Property http://www.owl-ontologies.com/unnamed.owl#owner
    String getOwner();

    RDFProperty getOwnerProperty();

    boolean hasOwner();

    void setOwner(String newOwner);
}


//~ Formatted by Jindent --- http://www.jindent.com
