/*
 * ObservationTextValuePanel.java
 *
 * Created on November 9, 2007, 1:44 PM
 */

package tr.com.srdc.icardea.careplanengine.agents.gui.consultingGUI;

import java.io.IOException;

import tr.com.srdc.icardea.careplanengine.entities.patientDataEntities.ObservationEntity;
import tr.com.srdc.icardea.careplanengine.entities.patientDataEntities.IndexEntity;
import tr.com.srdc.icardea.careplanengine.agents.monitoringAgent.MonitoringAgent;

import javax.swing.*;
import javax.swing.event.HyperlinkEvent;
import javax.swing.event.HyperlinkListener;

import edu.stanford.smi.protege.util.BrowserLauncher;

/**
 * 
 * @author mehmet
 */
public class ObservationIndexValuePanel extends javax.swing.JPanel {
	private JFrame parentFrame = null;
	private ObservationEntity observation = null;
	private String targetAID = null;
	private MonitoringAgent agent = null;

	public class HyperListener extends JFrame implements HyperlinkListener {

		@Override
		public void hyperlinkUpdate(HyperlinkEvent event) {
			if (event.getEventType() == HyperlinkEvent.EventType.ACTIVATED) {
				try {
					BrowserLauncher.openURL(event.getURL().toString());
					// explanationLabel.setPage(event.getURL());
				} catch (IOException ioe) {
					warnUser("Can't follow link to "
							+ event.getURL().toExternalForm() + ": " + ioe);
				}
			}
		}

		private void warnUser(String message) {
			JOptionPane.showMessageDialog(this, message, "Error",
					JOptionPane.ERROR_MESSAGE);
		}

	}

	/** Creates new form ObservationTextValuePanel */
	public ObservationIndexValuePanel() {
		initComponents();
	}

	public ObservationIndexValuePanel(JFrame consultingGUI,
			ObservationEntity obs, MonitoringAgent monitoringAgent,
			String senderAID, String consultSentence, String patientName,
			String patientID) {
		parentFrame = consultingGUI;
		observation = obs;
		targetAID = senderAID;
		this.agent = monitoringAgent;
		initComponents();
//		if (obs.getServiceCd() != null) {
//			this.conceptIDLabel.setText("Concept ID: "
//					+ obs.getServiceCd().getConceptID());
//			this.conceptNameLabel.setText("Concept Name: "
//					+ obs.getServiceCd().getConceptName());
//			this.conceptSourceLabel.setText("Concept Source: "
//					+ obs.getServiceCd().getConceptSource());
//		}
//		this.patientNameLabel.setText("<html><b>Patient Name: " + patientName
//				+ "</html>");
//		this.patientIDLabel.setText("Patient ID: " + patientID);
		this.explanationLabel.setText(consultSentence);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc=" Generated Code ">//GEN-BEGIN:initComponents
	private void initComponents() {

		upperPanel = new javax.swing.JPanel();
		sendConsultResult = new javax.swing.JButton();
		explanationLabel = new javax.swing.JEditorPane();
		explanationLabel.setContentType("text/html");
		explanationLabel.setEditable(false);
		HyperListener hl = new HyperListener();
		explanationLabel.addHyperlinkListener(hl);
		jTextField1 = new javax.swing.JTextField();
		jLabel1 = new javax.swing.JLabel();
//		belowPanel = new javax.swing.JPanel();
//		conceptNameLabel = new javax.swing.JLabel();
//		conceptIDLabel = new javax.swing.JLabel();
//		conceptSourceLabel = new javax.swing.JLabel();
//		patientDetailsPanel = new javax.swing.JPanel();
//		patientIDLabel = new javax.swing.JLabel();
//		patientNameLabel = new javax.swing.JLabel();

		upperPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
		sendConsultResult.setText("Send The Consult Result");
		sendConsultResult
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						sendConsultResultActionPerformed(evt);
					}
				});

		explanationLabel
				.setFont(new java.awt.Font("Bitstream Vera Sans", 1, 16));
		explanationLabel
				.setText("<html>Consult value for angina status of the patient</html>");

		jLabel1.setText("Value:");

		org.jdesktop.layout.GroupLayout upperPanelLayout = new org.jdesktop.layout.GroupLayout(
				upperPanel);
		upperPanel.setLayout(upperPanelLayout);
		upperPanelLayout
				.setHorizontalGroup(upperPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								upperPanelLayout
										.createSequentialGroup()
										.add(
												upperPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.LEADING)
														.add(
																upperPanelLayout
																		.createSequentialGroup()
																		.addContainerGap()
																		.add(
																				explanationLabel,
																				org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																				506,
																				Short.MAX_VALUE))
														.add(
																org.jdesktop.layout.GroupLayout.TRAILING,
																upperPanelLayout
																		.createSequentialGroup()
																		.addContainerGap(
																				367,
																				Short.MAX_VALUE)
																		.add(
																				sendConsultResult))
														.add(
																upperPanelLayout
																		.createSequentialGroup()
																		.add(
																				74,
																				74,
																				74)
																		.add(
																				jLabel1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				42,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				org.jdesktop.layout.LayoutStyle.RELATED)
																		.add(
																				jTextField1,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																				121,
																				org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap()));
		upperPanelLayout
				.setVerticalGroup(upperPanelLayout
						.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING)
						.add(
								upperPanelLayout
										.createSequentialGroup()
										.add(
												explanationLabel,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
												400,
												org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												org.jdesktop.layout.LayoutStyle.RELATED)
										.add(
												upperPanelLayout
														.createParallelGroup(
																org.jdesktop.layout.GroupLayout.BASELINE)
														.add(
																jTextField1,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
																org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
																org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
														.add(jLabel1)).add(38,
												38, 38).add(sendConsultResult)
										.addContainerGap()));

//		belowPanel.setBorder(javax.swing.BorderFactory
//				.createTitledBorder("Concept Details"));
//		conceptNameLabel.setText("Concept Name:");
//
//		conceptIDLabel.setText("Concept ID:");
//
//		conceptSourceLabel.setText("Concept Source:");

//		org.jdesktop.layout.GroupLayout belowPanelLayout = new org.jdesktop.layout.GroupLayout(
//				belowPanel);
//		belowPanel.setLayout(belowPanelLayout);
//		belowPanelLayout
//				.setHorizontalGroup(belowPanelLayout
//						.createParallelGroup(
//								org.jdesktop.layout.GroupLayout.LEADING)
//						.add(
//								belowPanelLayout
//										.createSequentialGroup()
//										.addContainerGap()
//										.add(
//												conceptNameLabel,
//												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//												184, Short.MAX_VALUE)
//										.add(25, 25, 25)
//										.add(
//												conceptIDLabel,
//												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//												144, Short.MAX_VALUE)
//										.add(14, 14, 14)
//										.add(
//												conceptSourceLabel,
//												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//												149, Short.MAX_VALUE)));
//		belowPanelLayout.setVerticalGroup(belowPanelLayout.createParallelGroup(
//				org.jdesktop.layout.GroupLayout.LEADING).add(
//				belowPanelLayout.createSequentialGroup().add(
//						belowPanelLayout.createParallelGroup(
//								org.jdesktop.layout.GroupLayout.BASELINE).add(
//								conceptNameLabel).add(conceptSourceLabel).add(
//								conceptIDLabel)).addContainerGap(
//						org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//						Short.MAX_VALUE)));

//		patientDetailsPanel.setBorder(javax.swing.BorderFactory
//				.createTitledBorder("Patient Details"));
//		patientIDLabel.setText("Patient ID:");
//
//		patientNameLabel.setText("Patient Name:");

//		org.jdesktop.layout.GroupLayout patientDetailsPanelLayout = new org.jdesktop.layout.GroupLayout(
//				patientDetailsPanel);
//		patientDetailsPanel.setLayout(patientDetailsPanelLayout);
//		patientDetailsPanelLayout
//				.setHorizontalGroup(patientDetailsPanelLayout
//						.createParallelGroup(
//								org.jdesktop.layout.GroupLayout.LEADING)
//						.add(
//								patientDetailsPanelLayout
//										.createSequentialGroup()
//										.addContainerGap()
//										.add(
//												patientNameLabel,
//												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//												195, Short.MAX_VALUE)
//										.add(14, 14, 14)
//										.add(
//												patientIDLabel,
//												org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//												142, Short.MAX_VALUE).add(165,
//												165, 165)));
//		patientDetailsPanelLayout.setVerticalGroup(patientDetailsPanelLayout
//				.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
//				.add(
//						patientDetailsPanelLayout.createParallelGroup(
//								org.jdesktop.layout.GroupLayout.BASELINE).add(
//								patientNameLabel).add(patientIDLabel)));

		org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(
				this);
		this.setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						layout.createParallelGroup(
								org.jdesktop.layout.GroupLayout.LEADING).add(
								upperPanel,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//								Short.MAX_VALUE).add(patientDetailsPanel,
//								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//								Short.MAX_VALUE).add(belowPanel,
//								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)).addContainerGap()));
		layout.setVerticalGroup(layout.createParallelGroup(
				org.jdesktop.layout.GroupLayout.LEADING).add(
				layout.createSequentialGroup().addContainerGap().add(
						upperPanel,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 500,
						org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//						.addPreferredGap(
//								org.jdesktop.layout.LayoutStyle.RELATED).add(
//								patientDetailsPanel,
//								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
//								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
//								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
//						.addPreferredGap(
//								org.jdesktop.layout.LayoutStyle.RELATED).add(
//								belowPanel,
//								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE,
//								41,
//								org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(
								org.jdesktop.layout.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
	}// </editor-fold>//GEN-END:initComponents

	private void sendConsultResultActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sendConsultResultActionPerformed
		IndexEntity indexEntity = new IndexEntity();
		String text = jTextField1.getText();
		float value;
		String a[];
		if (text.contains(",")) {
			a = text.split(",");
			// for (int i = 0; i < a.length; i++) {
			// String s = a[i];
			// Logger.getLogger(this.getClass().getName()).log(Level.DEBUG,
			// ("-'"+s+"'");
			// }
			if (a == null || a.length != 2) {
				JOptionPane
						.showMessageDialog(this, "Please check the number!!");
				return;
			}
			value = (float) (Integer.parseInt(a[0].trim()) + Double
					.parseDouble("0." + a[1].trim()));
		} else if (text.contains(".")) {
			a = text.split("\\.");
			// Logger.getLogger(this.getClass().getName()).log(Level.DEBUG,
			// ("contains '.':");
			// for (int i = 0; i < a.length; i++) {
			// String s = a[i];
			// Logger.getLogger(this.getClass().getName()).log(Level.DEBUG,
			// ("-'"+s+"'");
			// }
			if (a == null || a.length != 2) {
				JOptionPane
						.showMessageDialog(this, "Please check the number!!");
				return;
			}
			value = (float) (Integer.parseInt(a[0].trim()) + Double
					.parseDouble("0." + a[1].trim()));
		} else {
			try {
				value = Float.parseFloat(text);
			} catch (NumberFormatException e) {
				JOptionPane
						.showMessageDialog(this, "Please check the number!!");
				return;
			}
		}

		indexEntity.setIndex(value);
		indexEntity.setPrecision(1);
		observation.setValue(indexEntity);
		MonitoringAgent.getInstance().informConsultResult(targetAID,
				observation.toDataString());
		parentFrame.dispose();
	}// GEN-LAST:event_sendConsultResultActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	//private javax.swing.JPanel belowPanel;
	//private javax.swing.JLabel conceptIDLabel;
	//private javax.swing.JLabel conceptNameLabel;
	//private javax.swing.JLabel conceptSourceLabel;
	private javax.swing.JEditorPane explanationLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JTextField jTextField1;
	//private javax.swing.JPanel patientDetailsPanel;
	//private javax.swing.JLabel patientIDLabel;
	//private javax.swing.JLabel patientNameLabel;
	private javax.swing.JButton sendConsultResult;
	private javax.swing.JPanel upperPanel;
	// End of variables declaration//GEN-END:variables

}
